In [1]:
import pandas as pd

In [2]:
#data = "pokemon_data.csv"
#df = pd.read_csv(data)
#df.head()

In [4]:
#Reading data with issue
data_1 = pd.read_csv("pokemon_data.txt")
data_1.head(3)

  #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
0  1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...
1  2\tIvysaur\tGrass\tPoison\t60\t62\t63\t80\t80\...
2  3\tVenusaur\tGrass\tPoison\t80\t82\t83\t100\t1...

In [5]:
#solvinh the issue with the sep argument
data = "pokemon_data.txt" 
df = pd.read_csv(data, sep="\s+")
df.head(3)

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN

In [6]:
df.tail(3)

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
797,720,HoopaHoopa,Confined,Psychic,Ghost,80,110,60,150,130,70,6,TRUE,NaN,NaN,NaN
798,720,HoopaHoopa,Unbound,Psychic,Dark,80,160,60,170,130,80,6,TRUE,NaN,NaN,NaN
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,TRUE,NaN,NaN,NaN,NaN

# Reading data in pandas | headers - column - row - location

In [7]:
#header
df.columns

Index(['#', 'Name', 'Type', '1', 'Type.1', '2', 'HP', 'Attack', 'Defense',
       'Sp.', 'Atk', 'Sp..1', 'Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [8]:
#read specific column
df['Name'][0:3]

0    Bulbasaur
1      Ivysaur
2     Venusaur
Name: Name, dtype: object

In [9]:
df.Name[0:3]

0    Bulbasaur
1      Ivysaur
2     Venusaur
Name: Name, dtype: object

In [10]:
#Especific columns
df[['Name','Type','Attack']][0:4]

           Name      Type  Attack
0     Bulbasaur     Grass      65
1       Ivysaur     Grass      80
2      Venusaur     Grass     100
3  VenusaurMega  Venusaur     123

In [11]:
#Info of an entire row or multiples row with range ":"
df.iloc[0:3]

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN

In [12]:
#info in a specific row in an especific column
df.iloc[0,7]

65

In [13]:
#Iterate over ieach row
for index, row in df.iterrows():
    print(index, row['Defense'])

0 65
1 80
2 100
3 122
4 65
5 80
6 85
7 111
8 78
9 43
10 58
11 78
12 115
13 45
14 30
15 80
16 20
17 25
18 80
19 15
20 35
21 50
22 70
23 135
24 72
25 97
26 31
27 61
28 55
29 80
30 90
31 110
32 40
33 65
34 40
35 56
36 85
37 40
38 65
39 75
40 35
41 60
42 65
43 100
44 25
45 50
46 40
47 75
48 65
49 75
50 90
51 55
52 80
53 55
54 75
55 95
56 120
57 90
58 115
59 55
60 85
61 70
62 95
63 60
64 95
65 90
66 90
67 90
68 90
69 105
70 120
71 95
72 35
73 45
74 55
75 30
76 45
77 70
78 100
79 120
80 30
81 45
82 65
83 90
84 105
85 40
86 80
87 130
88 55
89 70
90 62
91 35
92 60
93 45
94 95
95 25
96 50
97 40
98 45
99 35
100 55
101 75
102 170
103 45
104 42
105 67
106 50
107 75
108 100
109 140
110 45
111 65
112 35
113 45
114 87
115 76
116 30
117 35
118 60
119 30
120 45
121 50
122 60
123 90
124 100
125 60
126 85
127 63
128 68
129 85
130 85
131 100
132 80
133 95
134 105
135 93
136 85
137 65
138 110
139 80
140 100
141 70
142 95
143 48
144 55
145 65
146 130
147 65
148 40
149 55
150 70
151 45
152 70
153 75
154 70
155 30
156 125
157 90
158 85
159 50
160 70
161 100
162 130
163 100
164 194
165 100
166 45
167 60
168 80
169 65
170 80
171 100
172 43
173 58
174 78
175 20
176 90
177 56
178 96
179 80
180 110
181 40
182 60
183 80
184 56
185 76
186 60
187 15
188 20
189 20
190 105
191 45
192 70
193 35
194 45
195 55
196 165
197 50
198 50
199 80
200 30
201 70
202 55
203 65
204 95
205 85
206 30
207 30
208 45
209 25
210 65
211 110
212 65
213 42
214 110
215 85
216 48
217 33
218 65
219 15
220 60
221 45
222 65
223 65
224 55
225 30
226 45
227 55
228 80
229 65
230 230
231 95
232 40
233 75
234 40
235 55
236 20
237 80
238 30
239 60
240 85
241 65
242 45
243 45
244 140
245 70
246 50
247 80
248 140
249 95
250 40
251 50
252 60
253 85
254 75
255 35
256 70
257 65
258 95
259 83
260 100
261 55
262 115
263 100
264 85
265 50
266 70
267 100
268 95
269 154
270 154
271 100
272 70
273 95
274 120
275 145
276 45
277 60
278 70
279 130
280 40
281 70
282 90
283 95
284 35
285 70
286 60
287 100
288 20
289 15
290 50
291 15
292 90
293 50
294 70
295 100
296 30
297 40
298 60
299 30
300 50
301 30
302 70
303 35
304 55
305 115
306 165
307 52
308 82
309 35
310 60
311 30
312 90
313 100
314 30
315 50
316 30
317 28
318 48
319 68
320 25
321 50
322 40
323 30
324 50
325 70
326 65
327 85
328 55
329 55
330 40
331 50
332 60
333 80
334 55
335 75
336 80
337 65
338 105
339 80
340 95
341 95
342 85
343 85
344 80
345 40
346 55
347 20
348 40
349 110
350 60
351 60
352 45
353 75
354 145
355 20
356 60
357 80
358 60
359 10
360 50
361 80
362 35
363 60
364 75
365 105
366 110
367 90
368 65
369 85
370 65
371 41
372 71
373 35
374 55
375 70
376 120
377 87
378 107
379 50
380 80
381 80
382 81
383 70
384 40
385 45
386 65
387 83
388 25
389 25
390 87
391 65
392 75
393 60
394 23
395 50
396 80
397 80
398 50
399 70
400 90
401 32
402 52
403 52
404 65
405 97
406 50
407 50
408 80
409 120
410 60
411 80
412 90
413 105
414 50
415 50
416 50
417 130
418 140
419 110
420 160
421 90
422 160
423 90
424 150
425 90
426 180
427 100
428 50
429 20
430 160
431 90
432 31
433 36
434 85
435 61
436 52
437 71
438 40
439 50
440 101
441 30
442 40
443 60
444 31
445 60
446 25
447 65
448 45
449 60
450 70
451 70
452 105
453 58
454 58
455 88
456 138
457 36
458 79
459 59
460 69
461 50
462 42
463 102
464 95
465 85
466 115
467 35
468 85
469 34
470 82
471 115
472 44
473 54
474 85
475 105
476 54
477 105
478 52
479 85
480 112
481 45
482 41
483 61
484 86
485 116
486 10
487 70
488 30
489 42
490 108
491 45
492 55
493 85
494 120
495 5
496 60
497 70
498 140
499 32
500 47
501 55
502 75
503 40
504 65
505 46
506 66
507 91
508 120
509 60
510 85
511 132
512 85
513 90
514 50
515 55
516 50
517 95
518 83
519 115
520 56
521 95
522 65
523 75
524 60
525 90
526 115
527 65
528 150
529 45
530 70
531 77
532 105
533 105
534 105
535 105
536 105
537 95
538 80
539 115
540 100
541 120
542 106
543 100
544 100
545 120
546 85
547 80
548 100
549 125
550 100
551 120
552 120
553 100
554 63
555 83
556 113
557 45
558 55
559 65
560 45
561 60
562 70
563 42
564 77
565 55
566 60
567 80
568 66
569 106
570 64
571 101
572 64
573 101
574 64
575 101
576 24
577 29
578 30
579 42
580 55
581 76
582 116
583 15
584 20
585 25
586 43
587 55
588 68
589 65
590 50
591 80
592 35
593 40
594 45
595 64
596 55
597 75
598 45
599 85
600 60
601 80
602 80
603 39
604 79
605 69
606 50
607 75
608 30
609 90
610 98
611 35
612 45
613 70
614 50
615 55
616 140
617 60
618 35
619 75
620 70
621 115
622 80
623 30
624 30
625 45
626 65
627 45
628 65
629 65
630 75
631 65
632 105
633 75
634 115
635 45
636 55
637 65
638 20
639 30
640 30
641 50
642 63
643 44
644 59
645 79
646 50
647 70
648 60
649 60
650 105
651 55
652 80
653 85
654 105
655 65
656 50
657 60
658 86
659 116
660 30
661 50
662 90
663 60
664 40
665 50
666 30
667 40
668 55
669 60
670 90
671 57
672 67
673 97
674 40
675 50
676 105
677 25
678 145
679 99
680 65
681 105
682 48
683 50
684 80
685 40
686 70
687 55
688 50
689 75
690 65
691 95
692 65
693 48
694 50
695 70
696 90
697 55
698 105
699 72
700 90
701 129
702 80
703 90
704 125
705 145
706 120
707 100
708 115
709 105
710 90
711 120
712 170
713 129
714 129
715 128
716 77
717 95
718 38
719 57
720 75
721 60
722 73
723 100
724 71
725 97
726 71
727 57
728 77
729 38
730 52
731 69
732 35
733 29
734 50
735 54
736 66
737 42
738 52
739 75
740 52
741 68
742 43
743 71
744 102
745 68
746 104
747 104
748 37
749 49
750 150
751 50
752 23
753 29
754 49
755 72
756 46
757 75
758 56
759 86
760 60
761 123
762 44
763 59
764 43
765 94
766 45
767 59
768 63
769 92
770 60
771 63
772 67
773 150
774 40
775 60
776 80
777 87
778 60
779 82
780 44
781 44
782 44
783 44
784 58
785 58
786 58
787 58
788 28
789 28
790 40
791 80
792 99
793 98
794 81
795 150
796 160
797 150
798 170
799 90

In [14]:
#finding specific data textual infromation
df.loc[df['Type']=="Fire"]

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
4,4,Charmander,Fire,39,52,43,60,50,65,1,FALSE,NaN,NaN,NaN,NaN,NaN
5,5,Charmeleon,Fire,58,64,58,80,65,80,1,FALSE,NaN,NaN,NaN,NaN,NaN
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,FALSE,NaN,NaN,NaN,NaN
42,37,Vulpix,Fire,38,41,40,50,65,65,1,FALSE,NaN,NaN,NaN,NaN,NaN
43,38,Ninetales,Fire,73,76,75,81,100,100,1,FALSE,NaN,NaN,NaN,NaN,NaN
63,58,Growlithe,Fire,55,70,45,70,50,60,1,FALSE,NaN,NaN,NaN,NaN,NaN
64,59,Arcanine,Fire,90,110,80,100,80,95,1,FALSE,NaN,NaN,NaN,NaN,NaN
83,77,Ponyta,Fire,50,85,55,65,65,90,1,FALSE,NaN,NaN,NaN,NaN,NaN
84,78,Rapidash,Fire,65,100,70,80,80,105,1,FALSE,NaN,NaN,NaN,NaN,NaN
135,126,Magmar,Fire,65,95,57,100,85,93,1,FALSE,NaN,NaN,NaN,NaN,NaN
147,136,Flareon,Fire,65,130,60,95,110,65,1,FALSE,NaN,NaN,NaN,NaN,NaN
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,TRUE,NaN,NaN,NaN,NaN
169,155,Cyndaquil,Fire,39,52,43,60,50,65,2,FALSE,NaN,NaN,NaN,NaN,NaN
170,156,Quilava,Fire,58,64,58,80,65,80,2,FALSE,NaN,NaN,NaN,NaN,NaN
171,157,Typhlosion,Fire,78,84,78,109,85,100,2,FALSE,NaN,NaN,NaN,NaN,NaN
236,218,Slugma,Fire,40,40,40,70,40,20,2,FALSE,NaN,NaN,NaN,NaN,NaN
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,FALSE,NaN,NaN,NaN,NaN
259,240,Magby,Fire,45,75,37,70,55,83,2,FALSE,NaN,NaN,NaN,NaN,NaN
263,244,Entei,Fire,115,115,85,90,75,100,2,TRUE,NaN,NaN,NaN,NaN,NaN
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,TRUE,NaN,NaN,NaN,NaN
276,255,Torchic,Fire,45,60,40,70,50,45,3,FALSE,NaN,NaN,NaN,NaN,NaN
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,FALSE,NaN,NaN,NaN,NaN
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,FALSE,NaN,NaN,NaN,NaN
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,FALSE,NaN,NaN,NaN,NaN
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,FALSE,NaN,NaN,NaN,NaN
355,324,Torkoal,Fire,70,85,140,85,70,20,3,FALSE,NaN,NaN,NaN,NaN,NaN
435,390,Chimchar,Fire,44,58,44,58,44,61,4,FALSE,NaN,NaN,NaN,NaN,NaN
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,FALSE,NaN,NaN,NaN,NaN
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,FALSE,NaN,NaN,NaN,NaN
518,467,Magmortar,Fire,75,95,67,125,95,83,4,FALSE,NaN,NaN,NaN,NaN,NaN
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,TRUE,NaN,NaN,NaN,NaN
557,498,Tepig,Fire,65,63,45,45,45,45,5,FALSE,NaN,NaN,NaN,NaN,NaN
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,FALSE,NaN,NaN,NaN,NaN
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,FALSE,NaN,NaN,NaN,NaN
572,513,Pansear,Fire,50,53,48,53,48,64,5,FALSE,NaN,NaN,NaN,NaN,NaN
573,514,Simisear,Fire,75,98,63,98,63,101,5,FALSE,NaN,NaN,NaN,NaN,NaN
614,554,Darumaka,Fire,70,90,45,15,45,50,5,FALSE,NaN,NaN,NaN,NaN,NaN
692,631,Heatmor,Fire,85,97,66,105,66,65,5,FALSE,NaN,NaN,NaN,NaN,NaN
721,653,Fennekin,Fire,40,45,40,62,60,60,6,FALSE,NaN,NaN,NaN,NaN,NaN
722,654,Braixen,Fire,59,59,58,90,70,73,6,FALSE,NaN,NaN,NaN,NaN,NaN
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,FALSE,NaN,NaN,NaN,NaN
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,FALSE,NaN,NaN,NaN,NaN
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,FALSE,NaN,NaN,NaN,NaN
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,FALSE,NaN,NaN,NaN,NaN
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,FALSE,NaN,NaN,NaN,NaN
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,TRUE,NaN,NaN,NaN,NaN

# Dataset numer's, stats infor and Sorting

In [15]:
df.head(3)

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN

In [16]:
df.describe()

,#,HP,Attack,Defense,Sp.,Generation,Legendary
count,800.000000,800.000000,800.000000,800.00000,800.000000,0.0,0.0
mean,362.813750,74.276250,72.857500,71.12875,41.832500,NaN,NaN
std,208.343798,33.250104,30.586338,31.25293,41.780485,NaN,NaN
min,1.000000,10.000000,10.000000,5.00000,1.000000,NaN,NaN
25%,184.750000,50.000000,50.000000,50.00000,3.000000,NaN,NaN
50%,364.500000,70.000000,67.500000,65.00000,32.000000,NaN,NaN
75%,539.250000,95.000000,90.000000,90.00000,75.250000,NaN,NaN
max,721.000000,230.000000,230.000000,230.00000,180.000000,NaN,NaN

In [17]:
df.sort_values('Name')

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,FALSE,NaN,NaN,NaN,NaN
511,460,AbomasnowMega,Abomasnow,Grass,Ice,90,132,105,132,105,30,4,FALSE,NaN,NaN,NaN
68,63,Abra,Psychic,25,20,15,105,55,90,1,FALSE,NaN,NaN,NaN,NaN,NaN
392,359,Absol,Dark,65,130,60,75,60,75,3,FALSE,NaN,NaN,NaN,NaN,NaN
393,359,AbsolMega,Absol,Dark,65,150,60,115,60,115,3,FALSE,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,60,105,60,120,60,105,5,FALSE,NaN,NaN,NaN,NaN,NaN
631,570,Zorua,Dark,40,65,40,80,40,65,5,FALSE,NaN,NaN,NaN,NaN,NaN
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,FALSE,NaN,NaN,NaN,NaN
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,FALSE,NaN,NaN,NaN,NaN
794,718,Zygarde50%,Forme,Dragon,Ground,108,100,121,81,95,95,6,TRUE,NaN,NaN,NaN

In [18]:
df.sort_values(['Type.1','HP'], ascending=[0,1])

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
533,479,RotomWash,Rotom,Electric,Water,50,65,107,105,107,86,4,FALSE,NaN,NaN,NaN
460,413,WormadamTrash,Cloak,Bug,Steel,60,69,95,69,95,36,4,FALSE,NaN,NaN,NaN
498,448,LucarioMega,Lucario,Fighting,Steel,70,145,88,140,70,112,4,FALSE,NaN,NaN,NaN
229,212,ScizorMega,Scizor,Bug,Steel,70,150,140,65,100,75,2,FALSE,NaN,NaN,NaN
616,555,DarmanitanZen,Mode,Fire,Psychic,105,30,105,140,105,55,5,FALSE,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,369,Relicanth,Water,Rock,100,90,130,45,65,55,3,FALSE,NaN,NaN,NaN,NaN
421,382,Kyogre,Water,100,100,90,150,140,90,3,TRUE,NaN,NaN,NaN,NaN,NaN
139,129,Magikarp,Water,20,10,55,15,20,80,1,FALSE,NaN,NaN,NaN,NaN,NaN
261,242,Blissey,Normal,255,10,10,75,135,55,2,FALSE,NaN,NaN,NaN,NaN,NaN
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,FALSE,NaN,NaN,NaN,NaN

# Making changes to the data

In [19]:
df.head(5)

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN
3,3,VenusaurMega,Venusaur,Grass,Poison,80,100,123,122,120,80,1,FALSE,NaN,NaN,NaN
4,4,Charmander,Fire,39,52,43,60,50,65,1,FALSE,NaN,NaN,NaN,NaN,NaN

In [20]:
df['Total'] = df['Attack'] + df['Defense'] + df['HP'] + df['Sp.']
df.head()

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN,224
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN,283
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN,363
3,3,VenusaurMega,Venusaur,Grass,Poison,80,100,123,122,120,80,1,FALSE,NaN,NaN,NaN,465
4,4,Charmander,Fire,39,52,43,60,50,65,1,FALSE,NaN,NaN,NaN,NaN,NaN,176

In [21]:
df = df.drop(columns=['Total'])
df.head()

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN
3,3,VenusaurMega,Venusaur,Grass,Poison,80,100,123,122,120,80,1,FALSE,NaN,NaN,NaN
4,4,Charmander,Fire,39,52,43,60,50,65,1,FALSE,NaN,NaN,NaN,NaN,NaN

# Sum values for several columns

In [22]:
df.columns

Index(['#', 'Name', 'Type', '1', 'Type.1', '2', 'HP', 'Attack', 'Defense',
       'Sp.', 'Atk', 'Sp..1', 'Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [23]:
df['Total'] = df.iloc[:,6:10].sum(axis=1)
df.head()

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN,224
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN,283
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN,363
3,3,VenusaurMega,Venusaur,Grass,Poison,80,100,123,122,120,80,1,FALSE,NaN,NaN,NaN,465
4,4,Charmander,Fire,39,52,43,60,50,65,1,FALSE,NaN,NaN,NaN,NaN,NaN,176

In [24]:
49+65+65+45

224

# export data

In [25]:
df.to_csv("modified_1.csv")

In [26]:
df.to_csv("modified_2.csv",index=False)

In [27]:
df.to_excel("modified_3.xlsx")

In [28]:
df.to_excel("modified_4.xlsx",index=False)

In [29]:
df.to_csv("modified_5.csv",index=False,sep="\t")

# Filtering data

In [30]:
df.loc[(df['Type']=="Grass") | (df['1']=="Poison")]

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN,224
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN,283
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN,363
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,FALSE,NaN,NaN,NaN,NaN,120
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,FALSE,NaN,NaN,NaN,NaN,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,56,61,65,48,45,38,6,FALSE,NaN,NaN,NaN,NaN,NaN,137
719,651,Quilladin,Grass,61,78,95,56,58,57,6,FALSE,NaN,NaN,NaN,NaN,NaN,177
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,FALSE,NaN,NaN,NaN,NaN,335
740,672,Skiddo,Grass,66,65,48,62,57,52,6,FALSE,NaN,NaN,NaN,NaN,NaN,177
741,673,Gogoat,Grass,123,100,62,97,81,68,6,FALSE,NaN,NaN,NaN,NaN,NaN,252

# reset index to zero

In [37]:
df.loc[(df['Type']=="Grass") & (df['1']=="Poison")]

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN,224
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN,283
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN,363
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,FALSE,NaN,NaN,NaN,NaN,225
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,FALSE,NaN,NaN,NaN,NaN,270
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,FALSE,NaN,NaN,NaN,NaN,335
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,FALSE,NaN,NaN,NaN,NaN,175
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,FALSE,NaN,NaN,NaN,NaN,235
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,FALSE,NaN,NaN,NaN,NaN,305
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,FALSE,NaN,NaN,NaN,NaN,290
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,FALSE,NaN,NaN,NaN,NaN,210
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,FALSE,NaN,NaN,NaN,NaN,385
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,FALSE,NaN,NaN,NaN,NaN,170
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,FALSE,NaN,NaN,NaN,NaN,265

In [45]:
new_df = df.loc[(df['Type']=="Grass") & (df['1']=="Poison")]
new_df.to_csv('filtered.csv')
new_df.head(2)

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN,224
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN,283

In [44]:
df.loc[df['Name'].str.contains('Gloom|Roselia')]

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,FALSE,NaN,NaN,NaN,NaN,270
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,FALSE,NaN,NaN,NaN,NaN,290

In [40]:
new_df = new_df.reset_index(drop=True)
new_df.tail(3)

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
11,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,FALSE,NaN,NaN,NaN,NaN,385
12,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,FALSE,NaN,NaN,NaN,NaN,170
13,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,FALSE,NaN,NaN,NaN,NaN,265

# Conditional Changes

In [50]:
df.loc[df['Type'] == 'Fire', 'Legendary'] = True
df.head()

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,FALSE,NaN,NaN,NaN,NaN,224
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE,NaN,NaN,NaN,NaN,283
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,FALSE,NaN,NaN,NaN,NaN,363
3,3,VenusaurMega,Venusaur,Grass,Poison,80,100,123,122,120,80,1,FALSE,NaN,NaN,NaN,465
4,4,Charmander,Fire,39,52,43,60,50,65,1,FALSE,NaN,NaN,NaN,NaN,True,176

In [59]:
df.loc[df['Total'] > 500, ['Attack', 'Defense']] = ['Test 1', 'Test 2']
df.tail()

,#,Name,Type,1,Type.1,2,HP,Attack,Defense,Sp.,Atk,Sp..1,Def,Speed,Generation,Legendary,Total
795,719,Diancie,Rock,Fairy,50,100,150,Test 1,Test 2,50,6,TRUE,NaN,NaN,NaN,NaN,450
796,719,DiancieMega,Diancie,Rock,Fairy,50,160,Test 1,Test 2,110,110,6,TRUE,NaN,NaN,NaN,540
797,720,HoopaHoopa,Confined,Psychic,Ghost,80,110,Test 1,Test 2,130,70,6,TRUE,NaN,NaN,NaN,450
798,720,HoopaHoopa,Unbound,Psychic,Dark,80,160,Test 1,Test 2,130,80,6,TRUE,NaN,NaN,NaN,520
799,721,Volcanion,Fire,Water,80,110,120,Test 1,Test 2,70,6,TRUE,NaN,NaN,NaN,True,410

# Agregate Statistics(Groupby)

In [71]:
df = pd.read_excel('pokemon_data.xlsx')
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [73]:
df.groupby(['Type 1']).mean()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714

In [75]:
df.groupby(['Type 1']).mean().sort_values('HP', ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000

In [76]:
df.groupby(['Type 1']).sum()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,23080,3925,4897,4880,3717,4471,4256,222,0.0
Dark,14302,2071,2740,2177,2314,2155,2361,125,2.0
Dragon,15180,2666,3588,2764,3099,2843,2657,124,12.0
Electric,15994,2631,3040,2917,3961,3243,3718,144,4.0
Fairy,7642,1260,1046,1117,1335,1440,826,70,1.0
Fighting,9824,1886,2613,1780,1434,1747,1784,91,0.0
Fire,17025,3635,4408,3524,4627,3755,3871,167,5.0
Flying,2711,283,315,265,377,290,410,22,2.0
Ghost,15568,2062,2361,2598,2539,2447,2059,134,2.0
Grass,24141,4709,5125,4956,5425,4930,4335,235,3.0
Ground,11401,2361,3064,2715,1807,2008,2045,101,4.0
Ice,10165,1728,1746,1714,1861,1831,1523,85,2.0
Normal,31279,7573,7200,5865,5470,6245,7012,299,2.0
Poison,7050,1883,2091,1927,1692,1803,1780,71,0.0
Psychic,21706,4026,4073,3858,5609,4918,4645,193,14.0
Rock,17280,2876,4086,4435,2787,3321,2460,152,4.0
Steel,11957,1761,2503,3412,1823,2177,1492,104,4.0
Water,33946,8071,8305,8170,8379,7898,7388,320,4.0

In [77]:
df.groupby(['Type 1']).count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112

In [79]:
df['count'] = 1
df.groupby(['Type 1']).count()['count']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,count
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,1
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,1
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,1
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,1
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,1
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,1

In [80]:
df['count'] = 1
df.groupby(['Type 1']).count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [81]:
df.groupby(['Type 1','Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

# Working with large amounts of data

In [86]:
for df in pd.read_csv('pokemon_data.csv',sep="\s+", chunksize=7):
    print("CUHNK DF")
    print(df)

CUHNK DF
                                         #,Name,Type  \
0  1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,F...
1   2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,FALSE
2  3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,...
3                                     3,VenusaurMega
4       4,Charmander,Fire,,39,52,43,60,50,65,1,FALSE
5       5,Charmeleon,Fire,,58,64,58,80,65,80,1,FALSE
6  6,Charizard,Fire,Flying,78,84,78,109,85,100,1,...

                                              1,Type  2,HP,Attack,Defense,Sp.  \
0                                                NaN                      NaN
1                                                NaN                      NaN
2                                                NaN                      NaN
3  Venusaur,Grass,Poison,80,100,123,122,120,80,1,...                      NaN
4                                                NaN                      NaN
5                                                NaN                      NaN
6                                                NaN                      NaN

   Atk,Sp.  Def,Speed,Generation,Legendary
0      NaN                             NaN
1      NaN                             NaN
2      NaN                             NaN
3      NaN                             NaN
4      NaN                             NaN
5      NaN                             NaN
6      NaN                             NaN
CUHNK DF
                                       #,Name,Type  \
7                                  6,CharizardMega
8                                  6,CharizardMega
9      7,Squirtle,Water,,44,48,65,50,64,43,1,FALSE
10    8,Wartortle,Water,,59,63,80,65,80,58,1,FALSE
11  9,Blastoise,Water,,79,83,100,85,105,78,1,FALSE
12                                 9,BlastoiseMega
13      10,Caterpie,Bug,,45,30,35,20,20,45,1,FALSE

                                            1,Type  \
7                                        Charizard
8                                        Charizard
9                                              NaN
10                                             NaN
11                                             NaN
12  Blastoise,Water,,79,103,120,135,115,78,1,FALSE
13                                             NaN

                        2,HP,Attack,Defense,Sp.  Atk,Sp.  \
7   X,Fire,Dragon,78,130,111,130,85,100,1,FALSE      NaN
8   Y,Fire,Flying,78,104,78,159,115,100,1,FALSE      NaN
9                                           NaN      NaN
10                                          NaN      NaN
11                                          NaN      NaN
12                                          NaN      NaN
13                                          NaN      NaN

    Def,Speed,Generation,Legendary
7                              NaN
8                              NaN
9                              NaN
10                             NaN
11                             NaN
12                             NaN
13                             NaN
CUHNK DF
                                          #,Name,Type  \
14          11,Metapod,Bug,,50,20,55,25,25,30,1,FALSE
15  12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,F...
16     13,Weedle,Bug,Poison,40,35,30,20,20,50,1,FALSE
17     14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,FALSE
18   15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,FALSE
19                                    15,BeedrillMega
20  16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,FALSE

                                             1,Type  2,HP,Attack,Defense,Sp.  \
14                                              NaN                      NaN
15                                              NaN                      NaN
16                                              NaN                      NaN
17                                              NaN                      NaN
18                                              NaN                      NaN
19  Beedrill,Bug,Poison,65,150,40,15,80,145,1,FALSE                      NaN
20                                              NaN                      NaN

    Atk,Sp.  Def,Speed,Generation,Legendary
14      NaN                             NaN
15      NaN                             NaN
16      NaN                             NaN
17      NaN                             NaN
18      NaN                             NaN
19      NaN                             NaN
20      NaN                             NaN
CUHNK DF
                                          #,Name,Type  \
21  17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1...
22  18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,...
23                                     18,PidgeotMega
24       19,Rattata,Normal,,30,56,35,25,35,72,1,FALSE
25      20,Raticate,Normal,,55,81,60,50,70,97,1,FALSE
26  21,Spearow,Normal,Flying,40,60,30,31,31,70,1,F...
27  22,Fearow,Normal,Flying,65,90,65,61,61,100,1,F...

                                               1,Type  \
21                                                NaN
22                                                NaN
23  Pidgeot,Normal,Flying,83,80,80,135,80,121,1,FALSE
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
21                      NaN      NaN                             NaN
22                      NaN      NaN                             NaN
23                      NaN      NaN                             NaN
24                      NaN      NaN                             NaN
25                      NaN      NaN                             NaN
26                      NaN      NaN                             NaN
27                      NaN      NaN                             NaN
CUHNK DF
                                         #,Name,Type  \
28        23,Ekans,Poison,,35,60,44,40,54,55,1,FALSE
29        24,Arbok,Poison,,60,85,69,65,79,80,1,FALSE
30    25,Pikachu,Electric,,35,55,40,50,50,90,1,FALSE
31    26,Raichu,Electric,,60,90,55,90,80,110,1,FALSE
32    27,Sandshrew,Ground,,50,75,85,20,30,40,1,FALSE
33  28,Sandslash,Ground,,75,100,110,45,55,65,1,FALSE
34                                        29,Nidoran

                                        1,Type  2,HP,Attack,Defense,Sp.  \
28                                         NaN                      NaN
29                                         NaN                      NaN
30                                         NaN                      NaN
31                                         NaN                      NaN
32                                         NaN                      NaN
33                                         NaN                      NaN
34  (Female),Poison,,55,47,52,40,40,41,1,FALSE                      NaN

    Atk,Sp.  Def,Speed,Generation,Legendary
28      NaN                             NaN
29      NaN                             NaN
30      NaN                             NaN
31      NaN                             NaN
32      NaN                             NaN
33      NaN                             NaN
34      NaN                             NaN
CUHNK DF
                                          #,Name,Type  \
35      30,Nidorina,Poison,,70,62,67,55,55,56,1,FALSE
36  31,Nidoqueen,Poison,Ground,90,92,87,75,85,76,1...
37                                         32,Nidoran
38      33,Nidorino,Poison,,61,72,57,55,55,65,1,FALSE
39  34,Nidoking,Poison,Ground,81,102,77,85,75,85,1...
40       35,Clefairy,Fairy,,70,45,48,60,65,35,1,FALSE
41       36,Clefable,Fairy,,95,70,73,95,90,60,1,FALSE

                                      1,Type  2,HP,Attack,Defense,Sp.  \
35                                       NaN                      NaN
36                                       NaN                      NaN
37  (Male),Poison,,46,57,40,40,40,50,1,FALSE                      NaN
38                                       NaN                      NaN
39                                       NaN                      NaN
40                                       NaN                      NaN
41                                       NaN                      NaN

    Atk,Sp.  Def,Speed,Generation,Legendary
35      NaN                             NaN
36      NaN                             NaN
37      NaN                             NaN
38      NaN                             NaN
39      NaN                             NaN
40      NaN                             NaN
41      NaN                             NaN
CUHNK DF
                                          #,Name,Type  1,Type  \
42          37,Vulpix,Fire,,38,41,40,50,65,65,1,FALSE     NaN
43     38,Ninetales,Fire,,73,76,75,81,100,100,1,FALSE     NaN
44  39,Jigglypuff,Normal,Fairy,115,45,20,45,25,20,...     NaN
45  40,Wigglytuff,Normal,Fairy,140,70,45,85,50,45,...     NaN
46   41,Zubat,Poison,Flying,40,45,35,30,40,55,1,FALSE     NaN
47  42,Golbat,Poison,Flying,75,80,70,65,75,90,1,FALSE     NaN
48   43,Oddish,Grass,Poison,45,50,55,75,65,30,1,FALSE     NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
42                      NaN      NaN                             NaN
43                      NaN      NaN                             NaN
44                      NaN      NaN                             NaN
45                      NaN      NaN                             NaN
46                      NaN      NaN                             NaN
47                      NaN      NaN                             NaN
48                      NaN      NaN                             NaN
CUHNK DF
                                          #,Name,Type  1,Type  \
49    44,Gloom,Grass,Poison,60,65,70,85,75,40,1,FALSE     NaN
50  45,Vileplume,Grass,Poison,75,80,85,110,90,50,1...     NaN
51       46,Paras,Bug,Grass,35,70,55,45,55,25,1,FALSE     NaN
52    47,Parasect,Bug,Grass,60,95,80,60,80,30,1,FALSE     NaN
53    48,Venonat,Bug,Poison,60,55,50,40,55,45,1,FALSE     NaN
54   49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,FALSE     NaN
55       50,Diglett,Ground,,10,55,25,35,45,95,1,FALSE     NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
49                      NaN      NaN                             NaN
50                      NaN      NaN                             NaN
51                      NaN      NaN                             NaN
52                      NaN      NaN                             NaN
53                      NaN      NaN                             NaN
54                      NaN      NaN                             NaN

55                      NaN      NaN                             NaN
CUHNK DF
                                         #,Name,Type  1,Type  \
56     51,Dugtrio,Ground,,35,80,50,50,70,120,1,FALSE     NaN
57       52,Meowth,Normal,,40,45,35,40,40,90,1,FALSE     NaN
58     53,Persian,Normal,,65,70,60,65,65,115,1,FALSE     NaN
59       54,Psyduck,Water,,50,52,48,65,50,55,1,FALSE     NaN
60       55,Golduck,Water,,80,82,78,95,80,85,1,FALSE     NaN
61     56,Mankey,Fighting,,40,80,35,35,45,70,1,FALSE     NaN
62  57,Primeape,Fighting,,65,105,60,60,70,95,1,FALSE     NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
56                      NaN      NaN                             NaN
57                      NaN      NaN                             NaN
58                      NaN      NaN                             NaN
59                      NaN      NaN                             NaN
60                      NaN      NaN                             NaN
61                      NaN      NaN                             NaN
62                      NaN      NaN                             NaN
CUHNK DF
                                          #,Name,Type  1,Type  \
63       58,Growlithe,Fire,,55,70,45,70,50,60,1,FALSE     NaN
64      59,Arcanine,Fire,,90,110,80,100,80,95,1,FALSE     NaN
65        60,Poliwag,Water,,40,50,40,40,40,90,1,FALSE     NaN
66      61,Poliwhirl,Water,,65,65,65,50,50,90,1,FALSE     NaN
67  62,Poliwrath,Water,Fighting,90,95,95,70,90,70,...     NaN
68        63,Abra,Psychic,,25,20,15,105,55,90,1,FALSE     NaN
69    64,Kadabra,Psychic,,40,35,30,120,70,105,1,FALSE     NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
63                      NaN      NaN                             NaN
64                      NaN      NaN                             NaN
65                      NaN      NaN                             NaN
66                      NaN      NaN                             NaN
67                      NaN      NaN                             NaN
68                      NaN      NaN                             NaN
69                      NaN      NaN                             NaN
CUHNK DF
                                          #,Name,Type  \
70   65,Alakazam,Psychic,,55,50,45,135,95,120,1,FALSE
71                                    65,AlakazamMega
72      66,Machop,Fighting,,70,80,50,35,35,35,1,FALSE
73    67,Machoke,Fighting,,80,100,70,50,60,45,1,FALSE
74    68,Machamp,Fighting,,90,130,80,65,85,55,1,FALSE
75  69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1...
76  70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1...

                                           1,Type  2,HP,Attack,Defense,Sp.  \
70                                            NaN                      NaN
71  Alakazam,Psychic,,55,50,65,175,95,150,1,FALSE                      NaN
72                                            NaN                      NaN
73                                            NaN                      NaN
74                                            NaN                      NaN
75                                            NaN                      NaN
76                                            NaN                      NaN

    Atk,Sp.  Def,Speed,Generation,Legendary
70      NaN                             NaN
71      NaN                             NaN
72      NaN                             NaN
73      NaN                             NaN
74      NaN                             NaN
75      NaN                             NaN
76      NaN                             NaN
CUHNK DF
                                          #,Name,Type  1,Type  \
77  71,Victreebel,Grass,Poison,80,105,65,100,70,70...     NaN
78  72,Tentacool,Water,Poison,40,40,35,50,100,70,1...     NaN
79  73,Tentacruel,Water,Poison,80,70,65,80,120,100...     NaN
80  74,Geodude,Rock,Ground,40,80,100,30,30,20,1,FALSE     NaN
81  75,Graveler,Rock,Ground,55,95,115,45,45,35,1,F...     NaN
82   76,Golem,Rock,Ground,80,120,130,55,65,45,1,FALSE     NaN
83          77,Ponyta,Fire,,50,85,55,65,65,90,1,FALSE     NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
77                      NaN      NaN                             NaN
78                      NaN      NaN                             NaN
79                      NaN      NaN                             NaN
80                      NaN      NaN                             NaN
81                      NaN      NaN                             NaN
82                      NaN      NaN                             NaN
83                      NaN      NaN                             NaN
CUHNK DF
                                          #,Name,Type  \
84      78,Rapidash,Fire,,65,100,70,80,80,105,1,FALSE
85  79,Slowpoke,Water,Psychic,90,65,65,40,40,15,1,...
86  80,Slowbro,Water,Psychic,95,75,110,100,80,30,1...
87                                     80,SlowbroMega
88  81,Magnemite,Electric,Steel,25,35,70,95,55,45,...
89  82,Magneton,Electric,Steel,50,60,95,120,70,70,...
90  83,Farfetch'd,Normal,Flying,52,65,55,58,62,60,...

                                               1,Type  \
84                                                NaN
85                                                NaN
86                                                NaN
87  Slowbro,Water,Psychic,95,75,180,130,80,30,1,FALSE
88                                                NaN
89                                                NaN
90                                                NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
84                      NaN      NaN                             NaN
85                      NaN      NaN                             NaN
86                      NaN      NaN                             NaN
87                      NaN      NaN                             NaN
88                      NaN      NaN                             NaN
89                      NaN      NaN                             NaN
90                      NaN      NaN                             NaN
CUHNK DF
                                          #,Name,Type  1,Type  \
91   84,Doduo,Normal,Flying,35,85,45,35,35,75,1,FALSE     NaN
92  85,Dodrio,Normal,Flying,60,110,70,60,60,100,1,...     NaN
93           86,Seel,Water,,65,45,55,45,70,45,1,FALSE     NaN
94     87,Dewgong,Water,Ice,90,70,80,70,95,70,1,FALSE     NaN
95        88,Grimer,Poison,,80,80,50,40,50,25,1,FALSE     NaN
96        89,Muk,Poison,,105,105,75,65,100,50,1,FALSE     NaN
97      90,Shellder,Water,,30,65,100,45,25,40,1,FALSE     NaN

    2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
91                      NaN      NaN                             NaN
92                      NaN      NaN                             NaN
93                      NaN      NaN                             NaN
94                      NaN      NaN                             NaN
95                      NaN      NaN                             NaN
96                      NaN      NaN                             NaN
97                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
98    91,Cloyster,Water,Ice,50,95,180,85,45,70,1,FALSE
99   92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,FALSE
100  93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,F...
101  94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,F...
102                                      94,GengarMega
103     95,Onix,Rock,Ground,35,45,160,30,45,70,1,FALSE
104      96,Drowzee,Psychic,,60,48,45,43,90,42,1,FALSE

                                              1,Type  2,HP,Attack,Defense,Sp.  \
98                                               NaN                      NaN
99                                               NaN                      NaN
100                                              NaN                      NaN
101                                              NaN                      NaN
102  Gengar,Ghost,Poison,60,65,80,170,95,130,1,FALSE                      NaN
103                                              NaN                      NaN
104                                              NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
98       NaN                             NaN
99       NaN                             NaN
100      NaN                             NaN
101      NaN                             NaN
102      NaN                             NaN
103      NaN                             NaN
104      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
105       97,Hypno,Psychic,,85,73,70,73,115,67,1,FALSE     NaN
106        98,Krabby,Water,,30,105,90,25,25,50,1,FALSE     NaN
107      99,Kingler,Water,,55,130,115,50,50,75,1,FALSE     NaN
108   100,Voltorb,Electric,,40,30,50,55,55,100,1,FALSE     NaN
109  101,Electrode,Electric,,60,50,70,80,80,140,1,F...     NaN
110  102,Exeggcute,Grass,Psychic,60,40,80,60,45,40,...     NaN
111  103,Exeggutor,Grass,Psychic,95,95,85,125,65,55...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
105                      NaN      NaN                             NaN
106                      NaN      NaN                             NaN
107                      NaN      NaN                             NaN
108                      NaN      NaN                             NaN
109                      NaN      NaN                             NaN
110                      NaN      NaN                             NaN
111                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
112       104,Cubone,Ground,,50,50,95,40,50,35,1,FALSE     NaN
113     105,Marowak,Ground,,60,80,110,50,80,45,1,FALSE     NaN
114  106,Hitmonlee,Fighting,,50,120,53,35,110,87,1,...     NaN
115  107,Hitmonchan,Fighting,,50,105,79,35,110,76,1...     NaN
116    108,Lickitung,Normal,,90,55,75,60,75,30,1,FALSE     NaN
117      109,Koffing,Poison,,40,65,95,60,45,35,1,FALSE     NaN
118     110,Weezing,Poison,,65,90,120,85,70,60,1,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
112                      NaN      NaN                             NaN
113                      NaN      NaN                             NaN
114                      NaN      NaN                             NaN
115                      NaN      NaN                             NaN
116                      NaN      NaN                             NaN
117                      NaN      NaN                             NaN
118                      NaN      NaN                             NaN

CUHNK DF
                                           #,Name,Type  \
119  111,Rhyhorn,Ground,Rock,80,85,95,30,30,25,1,FALSE
120  112,Rhydon,Ground,Rock,105,130,120,45,45,40,1,...
121      113,Chansey,Normal,,250,5,5,35,105,50,1,FALSE
122     114,Tangela,Grass,,65,55,115,100,40,60,1,FALSE
123  115,Kangaskhan,Normal,,105,95,80,40,80,90,1,FALSE
124                                 115,KangaskhanMega
125        116,Horsea,Water,,30,40,70,70,25,60,1,FALSE

                                                1,Type  \
119                                                NaN
120                                                NaN
121                                                NaN
122                                                NaN
123                                                NaN
124  Kangaskhan,Normal,,105,125,100,60,100,100,1,FALSE
125                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
119                      NaN      NaN                             NaN
120                      NaN      NaN                             NaN
121                      NaN      NaN                             NaN
122                      NaN      NaN                             NaN
123                      NaN      NaN                             NaN
124                      NaN      NaN                             NaN
125                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
126        117,Seadra,Water,,55,65,95,95,45,85,1,FALSE
127       118,Goldeen,Water,,45,67,60,35,50,63,1,FALSE
128       119,Seaking,Water,,80,92,65,65,80,68,1,FALSE
129        120,Staryu,Water,,30,45,55,70,55,85,1,FALSE
130  121,Starmie,Water,Psychic,60,75,85,100,85,115,...
131                                            122,Mr.
132  123,Scyther,Bug,Flying,70,110,80,55,80,105,1,F...

                                             1,Type  2,HP,Attack,Defense,Sp.  \
126                                             NaN                      NaN
127                                             NaN                      NaN
128                                             NaN                      NaN
129                                             NaN                      NaN
130                                             NaN                      NaN
131  Mime,Psychic,Fairy,40,45,65,100,120,90,1,FALSE                      NaN
132                                             NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
126      NaN                             NaN
127      NaN                             NaN
128      NaN                             NaN
129      NaN                             NaN
130      NaN                             NaN
131      NaN                             NaN
132      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
133    124,Jynx,Ice,Psychic,65,50,35,115,95,95,1,FALSE
134  125,Electabuzz,Electric,,65,83,57,95,85,105,1,...
135        126,Magmar,Fire,,65,95,57,100,85,93,1,FALSE
136        127,Pinsir,Bug,,65,125,100,55,70,85,1,FALSE
137                                     127,PinsirMega
138     128,Tauros,Normal,,75,100,95,40,70,110,1,FALSE
139      129,Magikarp,Water,,20,10,55,15,20,80,1,FALSE

                                             1,Type  2,HP,Attack,Defense,Sp.  \
133                                             NaN                      NaN
134                                             NaN                      NaN
135                                             NaN                      NaN
136                                             NaN                      NaN
137  Pinsir,Bug,Flying,65,155,120,65,90,105,1,FALSE                      NaN
138                                             NaN                      NaN
139                                             NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
133      NaN                             NaN
134      NaN                             NaN
135      NaN                             NaN
136      NaN                             NaN
137      NaN                             NaN
138      NaN                             NaN
139      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
140  130,Gyarados,Water,Flying,95,125,79,60,100,81,...
141                                   130,GyaradosMega
142    131,Lapras,Water,Ice,130,85,80,85,95,60,1,FALSE
143        132,Ditto,Normal,,48,48,48,48,48,48,1,FALSE
144        133,Eevee,Normal,,55,55,50,45,65,55,1,FALSE
145    134,Vaporeon,Water,,130,65,60,110,95,65,1,FALSE
146  135,Jolteon,Electric,,65,65,60,110,95,130,1,FALSE

                                               1,Type  \
140                                               NaN
141  Gyarados,Water,Dark,95,155,109,70,130,81,1,FALSE
142                                               NaN
143                                               NaN
144                                               NaN
145                                               NaN
146                                               NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
140                      NaN      NaN                             NaN
141                      NaN      NaN                             NaN
142                      NaN      NaN                             NaN
143                      NaN      NaN                             NaN
144                      NaN      NaN                             NaN
145                      NaN      NaN                             NaN
146                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
147      136,Flareon,Fire,,65,130,60,95,110,65,1,FALSE     NaN
148      137,Porygon,Normal,,65,60,70,85,75,40,1,FALSE     NaN
149  138,Omanyte,Rock,Water,35,40,100,90,55,35,1,FALSE     NaN
150  139,Omastar,Rock,Water,70,60,125,115,70,55,1,F...     NaN
151    140,Kabuto,Rock,Water,30,80,90,55,45,55,1,FALSE     NaN
152  141,Kabutops,Rock,Water,60,115,105,65,70,80,1,...     NaN
153  142,Aerodactyl,Rock,Flying,80,105,65,60,75,130...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
147                      NaN      NaN                             NaN
148                      NaN      NaN                             NaN
149                      NaN      NaN                             NaN
150                      NaN      NaN                             NaN
151                      NaN      NaN                             NaN
152                      NaN      NaN                             NaN
153                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
154                                 142,AerodactylMega
155   143,Snorlax,Normal,,160,110,65,65,110,30,1,FALSE
156  144,Articuno,Ice,Flying,90,85,100,95,125,85,1,...
157  145,Zapdos,Electric,Flying,90,90,85,125,90,100...
158  146,Moltres,Fire,Flying,90,100,90,125,85,90,1,...
159      147,Dratini,Dragon,,41,64,45,50,50,50,1,FALSE
160    148,Dragonair,Dragon,,61,84,65,70,70,70,1,FALSE

                                                1,Type  \
154  Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,F...
155                                                NaN
156                                                NaN
157                                                NaN
158                                                NaN
159                                                NaN
160                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
154                      NaN      NaN                             NaN
155                      NaN      NaN                             NaN
156                      NaN      NaN                             NaN
157                      NaN      NaN                             NaN
158                      NaN      NaN                             NaN
159                      NaN      NaN                             NaN
160                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
161  149,Dragonite,Dragon,Flying,91,134,95,100,100,...     NaN
162   150,Mewtwo,Psychic,,106,110,90,154,90,130,1,TRUE     NaN
163                                     150,MewtwoMega  Mewtwo
164                                     150,MewtwoMega  Mewtwo
165   151,Mew,Psychic,,100,100,100,100,100,100,1,FALSE     NaN
166     152,Chikorita,Grass,,45,49,65,49,65,45,2,FALSE     NaN
167       153,Bayleef,Grass,,60,62,80,63,80,60,2,FALSE     NaN

                               2,HP,Attack,Defense,Sp.  Atk,Sp.  \
161                                                NaN      NaN
162                                                NaN      NaN
163  X,Psychic,Fighting,106,190,100,154,100,130,1,TRUE      NaN
164           Y,Psychic,,106,150,70,194,120,140,1,TRUE      NaN
165                                                NaN      NaN
166                                                NaN      NaN
167                                                NaN      NaN

     Def,Speed,Generation,Legendary
161                             NaN
162                             NaN
163                             NaN
164                             NaN
165                             NaN
166                             NaN
167                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
168    154,Meganium,Grass,,80,82,100,83,100,80,2,FALSE     NaN
169      155,Cyndaquil,Fire,,39,52,43,60,50,65,2,FALSE     NaN
170        156,Quilava,Fire,,58,64,58,80,65,80,2,FALSE     NaN
171   157,Typhlosion,Fire,,78,84,78,109,85,100,2,FALSE     NaN
172      158,Totodile,Water,,50,65,64,44,48,43,2,FALSE     NaN
173      159,Croconaw,Water,,65,80,80,59,63,58,2,FALSE     NaN
174  160,Feraligatr,Water,,85,105,100,79,83,78,2,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
168                      NaN      NaN                             NaN
169                      NaN      NaN                             NaN
170                      NaN      NaN                             NaN
171                      NaN      NaN                             NaN
172                      NaN      NaN                             NaN
173                      NaN      NaN                             NaN
174                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
175      161,Sentret,Normal,,35,46,34,35,45,20,2,FALSE     NaN
176       162,Furret,Normal,,85,76,64,45,55,90,2,FALSE     NaN
177  163,Hoothoot,Normal,Flying,60,30,30,36,56,50,2...     NaN
178  164,Noctowl,Normal,Flying,100,50,50,76,96,70,2...     NaN
179    165,Ledyba,Bug,Flying,40,20,30,40,80,55,2,FALSE     NaN
180   166,Ledian,Bug,Flying,55,35,50,55,110,85,2,FALSE     NaN
181  167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
175                      NaN      NaN                             NaN
176                      NaN      NaN                             NaN
177                      NaN      NaN                             NaN
178                      NaN      NaN                             NaN
179                      NaN      NaN                             NaN
180                      NaN      NaN                             NaN
181                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
182   168,Ariados,Bug,Poison,70,90,70,60,60,40,2,FALSE     NaN
183  169,Crobat,Poison,Flying,85,90,80,70,80,130,2,...     NaN
184  170,Chinchou,Water,Electric,75,38,38,56,56,67,...     NaN
185  171,Lanturn,Water,Electric,125,58,58,76,76,67,...     NaN
186      172,Pichu,Electric,,20,40,15,35,35,60,2,FALSE     NaN
187        173,Cleffa,Fairy,,50,25,28,45,55,15,2,FALSE     NaN
188  174,Igglybuff,Normal,Fairy,90,30,15,40,20,15,2...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
182                      NaN      NaN                             NaN
183                      NaN      NaN                             NaN
184                      NaN      NaN                             NaN
185                      NaN      NaN                             NaN
186                      NaN      NaN                             NaN
187                      NaN      NaN                             NaN
188                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
189        175,Togepi,Fairy,,35,20,65,40,65,20,2,FALSE     NaN
190  176,Togetic,Fairy,Flying,55,40,85,80,105,40,2,...     NaN
191  177,Natu,Psychic,Flying,40,50,45,70,45,70,2,FALSE     NaN
192  178,Xatu,Psychic,Flying,65,75,70,95,70,95,2,FALSE     NaN
193     179,Mareep,Electric,,55,40,40,65,45,35,2,FALSE     NaN
194    180,Flaaffy,Electric,,70,55,55,80,60,45,2,FALSE     NaN
195  181,Ampharos,Electric,,90,75,85,115,90,55,2,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
189                      NaN      NaN                             NaN
190                      NaN      NaN                             NaN
191                      NaN      NaN                             NaN
192                      NaN      NaN                             NaN
193                      NaN      NaN                             NaN
194                      NaN      NaN                             NaN

195                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
196                                   181,AmpharosMega
197    182,Bellossom,Grass,,75,80,95,90,100,50,2,FALSE
198   183,Marill,Water,Fairy,70,20,50,20,50,40,2,FALSE
199  184,Azumarill,Water,Fairy,100,50,80,60,80,50,2...
200    185,Sudowoodo,Rock,,70,100,115,30,65,30,2,FALSE
201     186,Politoed,Water,,90,75,75,90,100,70,2,FALSE
202  187,Hoppip,Grass,Flying,35,35,40,35,55,50,2,FALSE

                                                1,Type  \
196  Ampharos,Electric,Dragon,90,95,105,165,110,45,...
197                                                NaN
198                                                NaN
199                                                NaN
200                                                NaN
201                                                NaN
202                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
196                      NaN      NaN                             NaN
197                      NaN      NaN                             NaN
198                      NaN      NaN                             NaN
199                      NaN      NaN                             NaN
200                      NaN      NaN                             NaN
201                      NaN      NaN                             NaN
202                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
203  188,Skiploom,Grass,Flying,55,45,50,45,65,80,2,...     NaN
204  189,Jumpluff,Grass,Flying,75,55,70,55,95,110,2...     NaN
205        190,Aipom,Normal,,55,70,55,40,55,85,2,FALSE     NaN
206       191,Sunkern,Grass,,30,30,30,30,30,30,2,FALSE     NaN
207     192,Sunflora,Grass,,75,75,55,105,85,30,2,FALSE     NaN
208     193,Yanma,Bug,Flying,65,65,45,75,45,95,2,FALSE     NaN
209  194,Wooper,Water,Ground,55,45,45,25,25,15,2,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
203                      NaN      NaN                             NaN
204                      NaN      NaN                             NaN
205                      NaN      NaN                             NaN
206                      NaN      NaN                             NaN
207                      NaN      NaN                             NaN
208                      NaN      NaN                             NaN
209                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
210  195,Quagsire,Water,Ground,95,85,85,65,65,35,2,...     NaN
211    196,Espeon,Psychic,,65,65,60,130,95,110,2,FALSE     NaN
212      197,Umbreon,Dark,,95,65,110,60,130,65,2,FALSE     NaN
213  198,Murkrow,Dark,Flying,60,85,42,85,42,91,2,FALSE     NaN
214  199,Slowking,Water,Psychic,95,75,80,100,110,30...     NaN
215    200,Misdreavus,Ghost,,60,60,60,85,85,85,2,FALSE     NaN
216       201,Unown,Psychic,,48,72,48,72,48,48,2,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
210                      NaN      NaN                             NaN
211                      NaN      NaN                             NaN
212                      NaN      NaN                             NaN
213                      NaN      NaN                             NaN
214                      NaN      NaN                             NaN
215                      NaN      NaN                             NaN
216                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
217  202,Wobbuffet,Psychic,,190,33,58,33,58,33,2,FALSE     NaN
218  203,Girafarig,Normal,Psychic,70,80,65,90,65,85...     NaN
219          204,Pineco,Bug,,50,65,90,35,35,15,2,FALSE     NaN
220  205,Forretress,Bug,Steel,75,90,140,60,60,40,2,...     NaN
221   206,Dunsparce,Normal,,100,70,70,65,65,45,2,FALSE     NaN
222  207,Gligar,Ground,Flying,65,75,105,35,65,85,2,...     NaN
223  208,Steelix,Steel,Ground,75,85,200,55,65,30,2,...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
217                      NaN      NaN                             NaN
218                      NaN      NaN                             NaN
219                      NaN      NaN                             NaN
220                      NaN      NaN                             NaN
221                      NaN      NaN                             NaN
222                      NaN      NaN                             NaN
223                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
224                                    208,SteelixMega
225      209,Snubbull,Fairy,,60,80,50,40,40,30,2,FALSE
226     210,Granbull,Fairy,,90,120,75,60,60,45,2,FALSE
227  211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,...
228   212,Scizor,Bug,Steel,70,130,100,55,80,65,2,FALSE
229                                     212,ScizorMega
230    213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,FALSE

                                               1,Type  \
224  Steelix,Steel,Ground,75,125,230,55,95,30,2,FALSE
225                                               NaN
226                                               NaN
227                                               NaN
228                                               NaN
229     Scizor,Bug,Steel,70,150,140,65,100,75,2,FALSE
230                                               NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
224                      NaN      NaN                             NaN
225                      NaN      NaN                             NaN
226                      NaN      NaN                             NaN
227                      NaN      NaN                             NaN
228                      NaN      NaN                             NaN
229                      NaN      NaN                             NaN
230                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
231  214,Heracross,Bug,Fighting,80,125,75,40,95,85,...
232                                  214,HeracrossMega
233    215,Sneasel,Dark,Ice,55,95,55,35,75,115,2,FALSE
234    216,Teddiursa,Normal,,60,80,50,50,50,40,2,FALSE
235    217,Ursaring,Normal,,90,130,75,75,75,55,2,FALSE
236         218,Slugma,Fire,,40,40,40,70,40,20,2,FALSE
237  219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,FALSE

                                                1,Type  \
231                                                NaN
232  Heracross,Bug,Fighting,80,185,115,40,105,75,2,...
233                                                NaN
234                                                NaN
235                                                NaN
236                                                NaN
237                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
231                      NaN      NaN                             NaN
232                      NaN      NaN                             NaN
233                      NaN      NaN                             NaN
234                      NaN      NaN                             NaN
235                      NaN      NaN                             NaN
236                      NaN      NaN                             NaN
237                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
238    220,Swinub,Ice,Ground,50,50,40,30,30,50,2,FALSE     NaN
239  221,Piloswine,Ice,Ground,100,100,80,60,60,50,2...     NaN
240   222,Corsola,Water,Rock,55,55,85,65,85,35,2,FALSE     NaN
241      223,Remoraid,Water,,35,65,35,65,35,65,2,FALSE     NaN
242   224,Octillery,Water,,75,105,75,105,75,45,2,FALSE     NaN
243  225,Delibird,Ice,Flying,45,55,45,65,45,75,2,FALSE     NaN
244  226,Mantine,Water,Flying,65,40,70,80,140,70,2,...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
238                      NaN      NaN                             NaN
239                      NaN      NaN                             NaN
240                      NaN      NaN                             NaN
241                      NaN      NaN                             NaN
242                      NaN      NaN                             NaN
243                      NaN      NaN                             NaN
244                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
245  227,Skarmory,Steel,Flying,65,80,140,40,70,70,2...
246   228,Houndour,Dark,Fire,45,60,30,80,50,65,2,FALSE
247  229,Houndoom,Dark,Fire,75,90,50,110,80,95,2,FALSE
248                                   229,HoundoomMega
249  230,Kingdra,Water,Dragon,75,95,95,95,95,85,2,F...
250       231,Phanpy,Ground,,90,60,60,40,40,40,2,FALSE
251    232,Donphan,Ground,,90,120,120,60,60,50,2,FALSE

                                             1,Type  2,HP,Attack,Defense,Sp.  \
245                                             NaN                      NaN
246                                             NaN                      NaN
247                                             NaN                      NaN
248  Houndoom,Dark,Fire,75,90,90,140,90,115,2,FALSE                      NaN
249                                             NaN                      NaN
250                                             NaN                      NaN
251                                             NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
245      NaN                             NaN
246      NaN                             NaN
247      NaN                             NaN
248      NaN                             NaN
249      NaN                             NaN
250      NaN                             NaN
251      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
252    233,Porygon2,Normal,,85,80,90,105,95,60,2,FALSE     NaN
253     234,Stantler,Normal,,73,95,62,85,65,85,2,FALSE     NaN
254     235,Smeargle,Normal,,55,20,35,20,45,75,2,FALSE     NaN
255    236,Tyrogue,Fighting,,35,35,35,35,35,35,2,FALSE     NaN
256  237,Hitmontop,Fighting,,50,95,95,35,110,70,2,F...     NaN
257  238,Smoochum,Ice,Psychic,45,30,15,85,65,65,2,F...     NaN
258     239,Elekid,Electric,,45,63,37,65,55,95,2,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
252                      NaN      NaN                             NaN
253                      NaN      NaN                             NaN
254                      NaN      NaN                             NaN
255                      NaN      NaN                             NaN
256                      NaN      NaN                             NaN
257                      NaN      NaN                             NaN

258                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
259          240,Magby,Fire,,45,75,37,70,55,83,2,FALSE     NaN
260    241,Miltank,Normal,,95,80,105,40,70,100,2,FALSE     NaN
261    242,Blissey,Normal,,255,10,10,75,135,55,2,FALSE     NaN
262   243,Raikou,Electric,,90,85,75,115,100,115,2,TRUE     NaN
263        244,Entei,Fire,,115,115,85,90,75,100,2,TRUE     NaN
264     245,Suicune,Water,,100,75,115,90,115,85,2,TRUE     NaN
265  246,Larvitar,Rock,Ground,50,64,50,45,50,41,2,F...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
259                      NaN      NaN                             NaN
260                      NaN      NaN                             NaN
261                      NaN      NaN                             NaN
262                      NaN      NaN                             NaN
263                      NaN      NaN                             NaN
264                      NaN      NaN                             NaN
265                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
266  247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,FALSE
267  248,Tyranitar,Rock,Dark,100,134,110,95,100,61,...
268                                  248,TyranitarMega
269  249,Lugia,Psychic,Flying,106,90,130,90,154,110...
270  250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,...
271  251,Celebi,Psychic,Grass,100,100,100,100,100,1...
272       252,Treecko,Grass,,40,45,35,65,55,70,3,FALSE

                                                1,Type  \
266                                                NaN
267                                                NaN
268  Tyranitar,Rock,Dark,100,164,150,95,120,71,2,FALSE
269                                                NaN
270                                                NaN
271                                                NaN
272                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
266                      NaN      NaN                             NaN
267                      NaN      NaN                             NaN
268                      NaN      NaN                             NaN
269                      NaN      NaN                             NaN
270                      NaN      NaN                             NaN
271                      NaN      NaN                             NaN
272                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
273       253,Grovyle,Grass,,50,65,45,85,65,95,3,FALSE
274    254,Sceptile,Grass,,70,85,65,105,85,120,3,FALSE
275                                   254,SceptileMega
276        255,Torchic,Fire,,45,60,40,70,50,45,3,FALSE
277  256,Combusken,Fire,Fighting,60,85,60,85,60,55,...
278  257,Blaziken,Fire,Fighting,80,120,70,110,70,80...
279                                   257,BlazikenMega

                                                1,Type  \
273                                                NaN
274                                                NaN
275  Sceptile,Grass,Dragon,70,110,75,145,85,145,3,F...
276                                                NaN
277                                                NaN
278                                                NaN
279  Blaziken,Fire,Fighting,80,160,80,130,80,100,3,...

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
273                      NaN      NaN                             NaN
274                      NaN      NaN                             NaN
275                      NaN      NaN                             NaN
276                      NaN      NaN                             NaN
277                      NaN      NaN                             NaN
278                      NaN      NaN                             NaN
279                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
280        258,Mudkip,Water,,50,70,50,50,50,40,3,FALSE
281  259,Marshtomp,Water,Ground,70,85,70,60,70,50,3...
282  260,Swampert,Water,Ground,100,110,90,85,90,60,...
283                                   260,SwampertMega
284      261,Poochyena,Dark,,35,55,35,30,30,35,3,FALSE
285      262,Mightyena,Dark,,70,90,70,60,60,70,3,FALSE
286    263,Zigzagoon,Normal,,38,30,41,30,41,60,3,FALSE

                                                1,Type  \
280                                                NaN
281                                                NaN
282                                                NaN
283  Swampert,Water,Ground,100,150,110,95,110,70,3,...
284                                                NaN
285                                                NaN
286                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
280                      NaN      NaN                             NaN
281                      NaN      NaN                             NaN
282                      NaN      NaN                             NaN
283                      NaN      NaN                             NaN
284                      NaN      NaN                             NaN
285                      NaN      NaN                             NaN
286                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
287     264,Linoone,Normal,,78,70,61,50,61,100,3,FALSE     NaN
288         265,Wurmple,Bug,,45,45,35,20,30,20,3,FALSE     NaN
289         266,Silcoon,Bug,,50,35,55,25,25,15,3,FALSE     NaN
290  267,Beautifly,Bug,Flying,60,70,50,100,50,65,3,...     NaN
291         268,Cascoon,Bug,,50,35,55,25,25,15,3,FALSE     NaN
292    269,Dustox,Bug,Poison,60,50,70,50,90,65,3,FALSE     NaN
293    270,Lotad,Water,Grass,40,30,30,40,50,30,3,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
287                      NaN      NaN                             NaN
288                      NaN      NaN                             NaN
289                      NaN      NaN                             NaN
290                      NaN      NaN                             NaN
291                      NaN      NaN                             NaN
292                      NaN      NaN                             NaN
293                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
294   271,Lombre,Water,Grass,60,50,50,60,70,50,3,FALSE     NaN
295  272,Ludicolo,Water,Grass,80,70,70,90,100,70,3,...     NaN
296        273,Seedot,Grass,,40,40,50,30,30,30,3,FALSE     NaN
297   274,Nuzleaf,Grass,Dark,70,70,40,60,40,60,3,FALSE     NaN
298  275,Shiftry,Grass,Dark,90,100,60,90,60,80,3,FALSE     NaN
299  276,Taillow,Normal,Flying,40,55,30,30,30,85,3,...     NaN
300  277,Swellow,Normal,Flying,60,85,60,50,50,125,3...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
294                      NaN      NaN                             NaN
295                      NaN      NaN                             NaN
296                      NaN      NaN                             NaN
297                      NaN      NaN                             NaN
298                      NaN      NaN                             NaN
299                      NaN      NaN                             NaN
300                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
301  278,Wingull,Water,Flying,40,30,30,55,30,85,3,F...
302  279,Pelipper,Water,Flying,60,50,100,85,70,65,3...
303  280,Ralts,Psychic,Fairy,28,25,25,45,35,40,3,FALSE
304  281,Kirlia,Psychic,Fairy,38,35,35,65,55,50,3,F...
305  282,Gardevoir,Psychic,Fairy,68,65,65,125,115,8...
306                                  282,GardevoirMega
307    283,Surskit,Bug,Water,40,30,32,50,52,65,3,FALSE

                                                1,Type  \
301                                                NaN
302                                                NaN
303                                                NaN
304                                                NaN
305                                                NaN
306  Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3...
307                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
301                      NaN      NaN                             NaN
302                      NaN      NaN                             NaN
303                      NaN      NaN                             NaN
304                      NaN      NaN                             NaN
305                      NaN      NaN                             NaN
306                      NaN      NaN                             NaN
307                      NaN      NaN                             NaN
CUHNK DF

                                           #,Name,Type  1,Type  \
308  284,Masquerain,Bug,Flying,70,60,62,80,82,60,3,...     NaN
309     285,Shroomish,Grass,,60,40,60,40,60,35,3,FALSE     NaN
310  286,Breloom,Grass,Fighting,60,130,80,60,60,70,...     NaN
311      287,Slakoth,Normal,,60,60,60,35,35,30,3,FALSE     NaN
312     288,Vigoroth,Normal,,80,80,80,55,55,90,3,FALSE     NaN
313  289,Slaking,Normal,,150,160,100,95,65,100,3,FALSE     NaN
314   290,Nincada,Bug,Ground,31,45,90,30,30,40,3,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
308                      NaN      NaN                             NaN
309                      NaN      NaN                             NaN
310                      NaN      NaN                             NaN
311                      NaN      NaN                             NaN
312                      NaN      NaN                             NaN
313                      NaN      NaN                             NaN
314                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
315  291,Ninjask,Bug,Flying,61,90,45,50,50,160,3,FALSE     NaN
316    292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,FALSE     NaN
317      293,Whismur,Normal,,64,51,23,51,23,28,3,FALSE     NaN
318      294,Loudred,Normal,,84,71,43,71,43,48,3,FALSE     NaN
319     295,Exploud,Normal,,104,91,63,91,73,68,3,FALSE     NaN
320   296,Makuhita,Fighting,,72,60,30,20,30,25,3,FALSE     NaN
321  297,Hariyama,Fighting,,144,120,60,40,60,50,3,F...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
315                      NaN      NaN                             NaN
316                      NaN      NaN                             NaN
317                      NaN      NaN                             NaN
318                      NaN      NaN                             NaN
319                      NaN      NaN                             NaN
320                      NaN      NaN                             NaN
321                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
322  298,Azurill,Normal,Fairy,50,20,40,20,40,20,3,F...
323      299,Nosepass,Rock,,30,45,135,45,90,30,3,FALSE
324       300,Skitty,Normal,,50,45,45,35,35,50,3,FALSE
325     301,Delcatty,Normal,,70,65,65,55,55,70,3,FALSE
326   302,Sableye,Dark,Ghost,50,75,75,65,65,50,3,FALSE
327                                    302,SableyeMega
328   303,Mawile,Steel,Fairy,50,85,85,55,55,50,3,FALSE

                                             1,Type  2,HP,Attack,Defense,Sp.  \
322                                             NaN                      NaN
323                                             NaN                      NaN
324                                             NaN                      NaN
325                                             NaN                      NaN
326                                             NaN                      NaN
327  Sableye,Dark,Ghost,50,85,125,85,115,20,3,FALSE                      NaN
328                                             NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
322      NaN                             NaN
323      NaN                             NaN
324      NaN                             NaN
325      NaN                             NaN
326      NaN                             NaN
327      NaN                             NaN
328      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
329                                     303,MawileMega
330     304,Aron,Steel,Rock,50,70,100,40,40,30,3,FALSE
331   305,Lairon,Steel,Rock,60,90,140,50,50,40,3,FALSE
332  306,Aggron,Steel,Rock,70,110,180,60,60,50,3,FALSE
333                                     306,AggronMega
334  307,Meditite,Fighting,Psychic,30,40,55,40,55,6...
335  308,Medicham,Fighting,Psychic,60,60,75,60,75,8...

                                             1,Type  2,HP,Attack,Defense,Sp.  \
329  Mawile,Steel,Fairy,50,105,125,55,95,50,3,FALSE                      NaN
330                                             NaN                      NaN
331                                             NaN                      NaN
332                                             NaN                      NaN
333       Aggron,Steel,,70,140,230,60,80,50,3,FALSE                      NaN
334                                             NaN                      NaN
335                                             NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
329      NaN                             NaN
330      NaN                             NaN
331      NaN                             NaN
332      NaN                             NaN
333      NaN                             NaN
334      NaN                             NaN
335      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
336                                   308,MedichamMega
337  309,Electrike,Electric,,40,45,40,65,40,65,3,FALSE
338  310,Manectric,Electric,,70,75,60,105,60,105,3,...
339                                  310,ManectricMega
340     311,Plusle,Electric,,60,50,40,85,75,95,3,FALSE
341      312,Minun,Electric,,60,40,50,75,85,95,3,FALSE
342         313,Volbeat,Bug,,65,73,55,47,75,85,3,FALSE

                                                1,Type  \
336  Medicham,Fighting,Psychic,60,100,85,80,85,100,...
337                                                NaN
338                                                NaN
339    Manectric,Electric,,70,75,80,135,80,135,3,FALSE
340                                                NaN
341                                                NaN
342                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
336                      NaN      NaN                             NaN
337                      NaN      NaN                             NaN
338                      NaN      NaN                             NaN
339                      NaN      NaN                             NaN
340                      NaN      NaN                             NaN
341                      NaN      NaN                             NaN
342                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
343        314,Illumise,Bug,,65,47,55,73,75,85,3,FALSE
344  315,Roselia,Grass,Poison,50,60,45,100,80,65,3,...
345       316,Gulpin,Poison,,70,43,53,43,53,40,3,FALSE
346      317,Swalot,Poison,,100,73,83,73,83,55,3,FALSE
347  318,Carvanha,Water,Dark,45,90,20,65,20,65,3,FALSE
348  319,Sharpedo,Water,Dark,70,120,40,95,40,95,3,F...
349                                   319,SharpedoMega

                                               1,Type  \
343                                               NaN
344                                               NaN
345                                               NaN
346                                               NaN
347                                               NaN
348                                               NaN
349  Sharpedo,Water,Dark,70,140,70,110,65,105,3,FALSE

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
343                      NaN      NaN                             NaN
344                      NaN      NaN                             NaN
345                      NaN      NaN                             NaN
346                      NaN      NaN                             NaN
347                      NaN      NaN                             NaN
348                      NaN      NaN                             NaN
349                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
350      320,Wailmer,Water,,130,70,35,70,35,60,3,FALSE
351      321,Wailord,Water,,170,90,45,90,45,60,3,FALSE
352    322,Numel,Fire,Ground,60,60,40,65,45,35,3,FALSE
353  323,Camerupt,Fire,Ground,70,100,70,105,75,40,3...
354                                   323,CameruptMega
355       324,Torkoal,Fire,,70,85,140,85,70,20,3,FALSE
356      325,Spoink,Psychic,,60,25,35,70,80,60,3,FALSE

                                                1,Type  \
350                                                NaN
351                                                NaN
352                                                NaN
353                                                NaN
354  Camerupt,Fire,Ground,70,120,100,145,105,20,3,F...
355                                                NaN
356                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
350                      NaN      NaN                             NaN
351                      NaN      NaN                             NaN
352                      NaN      NaN                             NaN
353                      NaN      NaN                             NaN
354                      NaN      NaN                             NaN
355                      NaN      NaN                             NaN
356                      NaN      NaN                             NaN

CUHNK DF
                                           #,Name,Type  1,Type  \
357    326,Grumpig,Psychic,,80,45,65,90,110,80,3,FALSE     NaN
358       327,Spinda,Normal,,60,60,60,60,60,60,3,FALSE     NaN
359    328,Trapinch,Ground,,45,100,45,45,45,10,3,FALSE     NaN
360  329,Vibrava,Ground,Dragon,50,70,50,50,50,70,3,...     NaN
361  330,Flygon,Ground,Dragon,80,100,80,80,80,100,3...     NaN
362        331,Cacnea,Grass,,50,85,40,85,40,35,3,FALSE     NaN
363  332,Cacturne,Grass,Dark,70,115,60,115,60,55,3,...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
357                      NaN      NaN                             NaN
358                      NaN      NaN                             NaN
359                      NaN      NaN                             NaN
360                      NaN      NaN                             NaN
361                      NaN      NaN                             NaN
362                      NaN      NaN                             NaN
363                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
364  333,Swablu,Normal,Flying,45,40,60,40,75,50,3,F...
365  334,Altaria,Dragon,Flying,75,70,90,70,105,80,3...
366                                    334,AltariaMega
367    335,Zangoose,Normal,,73,115,60,60,60,90,3,FALSE
368    336,Seviper,Poison,,73,100,60,100,60,65,3,FALSE
369  337,Lunatone,Rock,Psychic,70,55,65,95,85,70,3,...
370  338,Solrock,Rock,Psychic,70,95,85,55,65,70,3,F...

                                                1,Type  \
364                                                NaN
365                                                NaN
366  Altaria,Dragon,Fairy,75,110,110,110,105,80,3,F...
367                                                NaN
368                                                NaN
369                                                NaN
370                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
364                      NaN      NaN                             NaN
365                      NaN      NaN                             NaN
366                      NaN      NaN                             NaN
367                      NaN      NaN                             NaN
368                      NaN      NaN                             NaN
369                      NaN      NaN                             NaN
370                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
371  339,Barboach,Water,Ground,50,48,43,46,41,60,3,...     NaN
372  340,Whiscash,Water,Ground,110,78,73,76,71,60,3...     NaN
373      341,Corphish,Water,,43,80,65,50,35,35,3,FALSE     NaN
374  342,Crawdaunt,Water,Dark,63,120,85,90,55,55,3,...     NaN
375  343,Baltoy,Ground,Psychic,40,40,55,40,70,55,3,...     NaN
376  344,Claydol,Ground,Psychic,60,70,105,70,120,75...     NaN
377    345,Lileep,Rock,Grass,66,41,77,61,87,23,3,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
371                      NaN      NaN                             NaN
372                      NaN      NaN                             NaN
373                      NaN      NaN                             NaN
374                      NaN      NaN                             NaN
375                      NaN      NaN                             NaN
376                      NaN      NaN                             NaN
377                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
378  346,Cradily,Rock,Grass,86,81,97,81,107,43,3,FALSE     NaN
379     347,Anorith,Rock,Bug,45,95,50,40,50,75,3,FALSE     NaN
380   348,Armaldo,Rock,Bug,75,125,100,70,80,45,3,FALSE     NaN
381        349,Feebas,Water,,20,15,20,10,55,80,3,FALSE     NaN
382     350,Milotic,Water,,95,60,79,100,125,81,3,FALSE     NaN
383     351,Castform,Normal,,70,70,70,70,70,70,3,FALSE     NaN
384     352,Kecleon,Normal,,60,90,70,60,120,40,3,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
378                      NaN      NaN                             NaN
379                      NaN      NaN                             NaN
380                      NaN      NaN                             NaN
381                      NaN      NaN                             NaN
382                      NaN      NaN                             NaN
383                      NaN      NaN                             NaN
384                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
385       353,Shuppet,Ghost,,44,75,35,63,33,45,3,FALSE
386      354,Banette,Ghost,,64,115,65,83,63,65,3,FALSE
387                                    354,BanetteMega
388       355,Duskull,Ghost,,20,40,90,30,90,25,3,FALSE
389    356,Dusclops,Ghost,,40,70,130,60,130,25,3,FALSE
390  357,Tropius,Grass,Flying,99,68,83,72,87,51,3,F...
391    358,Chimecho,Psychic,,65,50,70,95,80,65,3,FALSE

                                        1,Type  2,HP,Attack,Defense,Sp.  \
385                                        NaN                      NaN
386                                        NaN                      NaN
387  Banette,Ghost,,64,165,75,93,83,75,3,FALSE                      NaN
388                                        NaN                      NaN
389                                        NaN                      NaN
390                                        NaN                      NaN
391                                        NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
385      NaN                             NaN
386      NaN                             NaN
387      NaN                             NaN
388      NaN                             NaN
389      NaN                             NaN
390      NaN                             NaN
391      NaN                             NaN
CUHNK DF
                                        #,Name,Type  \
392      359,Absol,Dark,,65,130,60,75,60,75,3,FALSE
393                                   359,AbsolMega
394   360,Wynaut,Psychic,,95,23,48,23,48,23,3,FALSE
395      361,Snorunt,Ice,,50,50,50,50,50,50,3,FALSE
396       362,Glalie,Ice,,80,80,80,80,80,80,3,FALSE
397                                  362,GlalieMega
398  363,Spheal,Ice,Water,70,40,50,55,50,25,3,FALSE

                                       1,Type  2,HP,Attack,Defense,Sp.  \
392                                       NaN                      NaN
393  Absol,Dark,,65,150,60,115,60,115,3,FALSE                      NaN
394                                       NaN                      NaN
395                                       NaN                      NaN
396                                       NaN                      NaN
397  Glalie,Ice,,80,120,80,120,80,100,3,FALSE                      NaN
398                                       NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
392      NaN                             NaN
393      NaN                             NaN
394      NaN                             NaN
395      NaN                             NaN
396      NaN                             NaN
397      NaN                             NaN
398      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
399     364,Sealeo,Ice,Water,90,60,70,75,70,45,3,FALSE     NaN
400   365,Walrein,Ice,Water,110,80,90,95,90,65,3,FALSE     NaN
401      366,Clamperl,Water,,35,64,85,74,55,32,3,FALSE     NaN
402     367,Huntail,Water,,55,104,105,94,75,52,3,FALSE     NaN
403    368,Gorebyss,Water,,55,84,105,114,75,52,3,FALSE     NaN
404  369,Relicanth,Water,Rock,100,90,130,45,65,55,3...     NaN
405       370,Luvdisc,Water,,43,30,55,40,65,97,3,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
399                      NaN      NaN                             NaN
400                      NaN      NaN                             NaN
401                      NaN      NaN                             NaN
402                      NaN      NaN                             NaN
403                      NaN      NaN                             NaN
404                      NaN      NaN                             NaN
405                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
406        371,Bagon,Dragon,,45,75,60,40,30,50,3,FALSE
407     372,Shelgon,Dragon,,65,95,100,60,50,50,3,FALSE
408  373,Salamence,Dragon,Flying,95,135,80,110,80,1...
409                                  373,SalamenceMega
410  374,Beldum,Steel,Psychic,40,55,80,35,60,30,3,F...
411  375,Metang,Steel,Psychic,60,75,100,55,80,50,3,...
412  376,Metagross,Steel,Psychic,80,135,130,95,90,7...

                                                1,Type  \
406                                                NaN
407                                                NaN
408                                                NaN
409  Salamence,Dragon,Flying,95,145,130,120,90,120,...
410                                                NaN
411                                                NaN
412                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
406                      NaN      NaN                             NaN
407                      NaN      NaN                             NaN
408                      NaN      NaN                             NaN
409                      NaN      NaN                             NaN
410                      NaN      NaN                             NaN
411                      NaN      NaN                             NaN
412                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
413                                  376,MetagrossMega
414     377,Regirock,Rock,,80,100,200,50,100,50,3,TRUE
415        378,Regice,Ice,,80,50,100,100,200,50,3,TRUE
416    379,Registeel,Steel,,80,75,150,75,150,50,3,TRUE
417  380,Latias,Dragon,Psychic,80,80,90,110,130,110...
418                                     380,LatiasMega
419  381,Latios,Dragon,Psychic,80,90,80,130,110,110...

                                                1,Type  \
413  Metagross,Steel,Psychic,80,145,150,105,110,110...
414                                                NaN
415                                                NaN
416                                                NaN
417                                                NaN
418  Latias,Dragon,Psychic,80,100,120,140,150,110,3...
419                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
413                      NaN      NaN                             NaN
414                      NaN      NaN                             NaN
415                      NaN      NaN                             NaN
416                      NaN      NaN                             NaN
417                      NaN      NaN                             NaN
418                      NaN      NaN                             NaN
419                      NaN      NaN                             NaN

CUHNK DF
                                           #,Name,Type  \
420                                     381,LatiosMega
421     382,Kyogre,Water,,100,100,90,150,140,90,3,TRUE
422                                   382,KyogrePrimal
423   383,Groudon,Ground,,100,150,140,100,90,90,3,TRUE
424                                  383,GroudonPrimal
425  384,Rayquaza,Dragon,Flying,105,150,90,150,90,9...
426                                   384,RayquazaMega

                                                1,Type  \
420  Latios,Dragon,Psychic,80,130,100,160,120,110,3...
421                                                NaN
422         Kyogre,Water,,100,150,90,180,160,90,3,TRUE
423                                                NaN
424   Groudon,Ground,Fire,100,180,160,150,90,90,3,TRUE
425                                                NaN
426  Rayquaza,Dragon,Flying,105,180,100,180,100,115...

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
420                      NaN      NaN                             NaN
421                      NaN      NaN                             NaN
422                      NaN      NaN                             NaN
423                      NaN      NaN                             NaN
424                      NaN      NaN                             NaN
425                      NaN      NaN                             NaN
426                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
427  385,Jirachi,Steel,Psychic,100,100,100,100,100,...
428                                   386,DeoxysNormal
429                                   386,DeoxysAttack
430                                  386,DeoxysDefense
431                                    386,DeoxysSpeed
432       387,Turtwig,Grass,,55,68,64,45,55,31,4,FALSE
433        388,Grotle,Grass,,75,89,85,55,65,36,4,FALSE

                                         1,Type  2,HP,Attack,Defense,Sp.  \
427                                         NaN                      NaN
428  Forme,Psychic,,50,150,50,150,50,150,3,TRUE                      NaN
429  Forme,Psychic,,50,180,20,180,20,150,3,TRUE                      NaN
430   Forme,Psychic,,50,70,160,70,160,90,3,TRUE                      NaN
431    Forme,Psychic,,50,95,90,95,90,180,3,TRUE                      NaN
432                                         NaN                      NaN
433                                         NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
427      NaN                             NaN
428      NaN                             NaN
429      NaN                             NaN
430      NaN                             NaN
431      NaN                             NaN
432      NaN                             NaN
433      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
434  389,Torterra,Grass,Ground,95,109,105,75,85,56,...     NaN
435       390,Chimchar,Fire,,44,58,44,58,44,61,4,FALSE     NaN
436  391,Monferno,Fire,Fighting,64,78,52,78,52,81,4...     NaN
437  392,Infernape,Fire,Fighting,76,104,71,104,71,1...     NaN
438        393,Piplup,Water,,53,51,53,61,56,40,4,FALSE     NaN
439      394,Prinplup,Water,,64,66,68,81,76,50,4,FALSE     NaN
440  395,Empoleon,Water,Steel,84,86,88,111,101,60,4...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
434                      NaN      NaN                             NaN
435                      NaN      NaN                             NaN
436                      NaN      NaN                             NaN
437                      NaN      NaN                             NaN
438                      NaN      NaN                             NaN
439                      NaN      NaN                             NaN
440                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
441  396,Starly,Normal,Flying,40,55,30,30,30,60,4,F...     NaN
442  397,Staravia,Normal,Flying,55,75,50,40,40,80,4...     NaN
443  398,Staraptor,Normal,Flying,85,120,70,50,60,10...     NaN
444       399,Bidoof,Normal,,59,45,40,35,40,31,4,FALSE     NaN
445  400,Bibarel,Normal,Water,79,85,60,55,60,71,4,F...     NaN
446       401,Kricketot,Bug,,37,25,41,25,41,25,4,FALSE     NaN
447      402,Kricketune,Bug,,77,85,51,55,51,65,4,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
441                      NaN      NaN                             NaN
442                      NaN      NaN                             NaN
443                      NaN      NaN                             NaN
444                      NaN      NaN                             NaN
445                      NaN      NaN                             NaN
446                      NaN      NaN                             NaN
447                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
448      403,Shinx,Electric,,45,65,34,40,34,45,4,FALSE     NaN
449      404,Luxio,Electric,,60,85,49,60,49,60,4,FALSE     NaN
450    405,Luxray,Electric,,80,120,79,95,79,70,4,FALSE     NaN
451   406,Budew,Grass,Poison,40,30,35,50,70,55,4,FALSE     NaN
452  407,Roserade,Grass,Poison,60,70,65,125,105,90,...     NaN
453      408,Cranidos,Rock,,67,125,40,30,30,58,4,FALSE     NaN
454     409,Rampardos,Rock,,97,165,60,65,50,58,4,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
448                      NaN      NaN                             NaN
449                      NaN      NaN                             NaN
450                      NaN      NaN                             NaN
451                      NaN      NaN                             NaN
452                      NaN      NaN                             NaN
453                      NaN      NaN                             NaN
454                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
455  410,Shieldon,Rock,Steel,30,42,118,42,88,30,4,F...
456  411,Bastiodon,Rock,Steel,60,52,168,47,138,30,4...
457           412,Burmy,Bug,,40,29,45,29,45,36,4,FALSE
458                                  413,WormadamPlant
459                                  413,WormadamSandy
460                                  413,WormadamTrash
461    414,Mothim,Bug,Flying,70,94,50,94,50,66,4,FALSE

                                          1,Type  2,HP,Attack,Defense,Sp.  \
455                                          NaN                      NaN
456                                          NaN                      NaN
457                                          NaN                      NaN
458   Cloak,Bug,Grass,60,59,85,79,105,36,4,FALSE                      NaN
459  Cloak,Bug,Ground,60,79,105,59,85,36,4,FALSE                      NaN
460    Cloak,Bug,Steel,60,69,95,69,95,36,4,FALSE                      NaN
461                                          NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
455      NaN                             NaN
456      NaN                             NaN
457      NaN                             NaN
458      NaN                             NaN
459      NaN                             NaN
460      NaN                             NaN
461      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
462    415,Combee,Bug,Flying,30,30,42,30,42,70,4,FALSE     NaN
463  416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4...     NaN
464  417,Pachirisu,Electric,,60,45,70,45,90,95,4,FALSE     NaN
465        418,Buizel,Water,,55,65,35,60,30,85,4,FALSE     NaN
466    419,Floatzel,Water,,85,105,55,85,50,115,4,FALSE     NaN
467       420,Cherubi,Grass,,45,35,45,62,53,35,4,FALSE     NaN
468       421,Cherrim,Grass,,70,60,70,87,78,85,4,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
462                      NaN      NaN                             NaN
463                      NaN      NaN                             NaN
464                      NaN      NaN                             NaN
465                      NaN      NaN                             NaN
466                      NaN      NaN                             NaN
467                      NaN      NaN                             NaN
468                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
469       422,Shellos,Water,,76,48,48,57,62,34,4,FALSE     NaN
470  423,Gastrodon,Water,Ground,111,83,68,92,82,39,...     NaN
471    424,Ambipom,Normal,,75,100,66,60,66,115,4,FALSE     NaN
472  425,Drifloon,Ghost,Flying,90,50,34,60,44,70,4,...     NaN
473  426,Drifblim,Ghost,Flying,150,80,44,90,54,80,4...     NaN
474      427,Buneary,Normal,,55,66,44,44,56,85,4,FALSE     NaN
475     428,Lopunny,Normal,,65,76,84,54,96,105,4,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
469                      NaN      NaN                             NaN
470                      NaN      NaN                             NaN
471                      NaN      NaN                             NaN
472                      NaN      NaN                             NaN
473                      NaN      NaN                             NaN
474                      NaN      NaN                             NaN
475                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
476                                    428,LopunnyMega
477  429,Mismagius,Ghost,,60,60,60,105,105,105,4,FALSE
478  430,Honchkrow,Dark,Flying,100,125,52,105,52,71...
479      431,Glameow,Normal,,49,55,42,42,37,85,4,FALSE
480     432,Purugly,Normal,,71,82,64,64,59,112,4,FALSE
481   433,Chingling,Psychic,,45,30,50,65,50,45,4,FALSE
482   434,Stunky,Poison,Dark,63,63,47,41,41,74,4,FALSE

                                                1,Type  \
476  Lopunny,Normal,Fighting,65,136,94,54,96,135,4,...
477                                                NaN
478                                                NaN
479                                                NaN
480                                                NaN
481                                                NaN
482                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
476                      NaN      NaN                             NaN
477                      NaN      NaN                             NaN
478                      NaN      NaN                             NaN
479                      NaN      NaN                             NaN
480                      NaN      NaN                             NaN
481                      NaN      NaN                             NaN
482                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
483  435,Skuntank,Poison,Dark,103,93,67,71,61,84,4,...
484  436,Bronzor,Steel,Psychic,57,24,86,24,86,23,4,...
485  437,Bronzong,Steel,Psychic,67,89,116,79,116,33...
486         438,Bonsly,Rock,,50,80,95,10,45,10,4,FALSE
487                                           439,Mime
488       440,Happiny,Normal,,100,5,5,15,65,30,4,FALSE
489  441,Chatot,Normal,Flying,76,65,45,92,42,91,4,F...

                                          1,Type  2,HP,Attack,Defense,Sp.  \
483                                          NaN                      NaN
484                                          NaN                      NaN
485                                          NaN                      NaN
486                                          NaN                      NaN
487  Jr.,Psychic,Fairy,20,25,45,70,90,60,4,FALSE                      NaN
488                                          NaN                      NaN
489                                          NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
483      NaN                             NaN
484      NaN                             NaN
485      NaN                             NaN
486      NaN                             NaN
487      NaN                             NaN
488      NaN                             NaN
489      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
490  442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,4...
491  443,Gible,Dragon,Ground,58,70,45,40,45,42,4,FALSE
492  444,Gabite,Dragon,Ground,68,90,65,50,55,82,4,F...
493  445,Garchomp,Dragon,Ground,108,130,95,80,85,10...
494                                   445,GarchompMega
495     446,Munchlax,Normal,,135,85,40,40,85,5,4,FALSE
496      447,Riolu,Fighting,,40,70,40,35,40,60,4,FALSE

                                                1,Type  \
490                                                NaN
491                                                NaN
492                                                NaN
493                                                NaN
494  Garchomp,Dragon,Ground,108,170,115,120,95,92,4...
495                                                NaN
496                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
490                      NaN      NaN                             NaN
491                      NaN      NaN                             NaN
492                      NaN      NaN                             NaN
493                      NaN      NaN                             NaN
494                      NaN      NaN                             NaN
495                      NaN      NaN                             NaN
496                      NaN      NaN                             NaN

CUHNK DF
                                           #,Name,Type  \
497  448,Lucario,Fighting,Steel,70,110,70,115,70,90...
498                                    448,LucarioMega
499   449,Hippopotas,Ground,,68,72,78,38,42,32,4,FALSE
500  450,Hippowdon,Ground,,108,112,118,68,72,47,4,F...
501   451,Skorupi,Poison,Bug,40,50,90,30,55,65,4,FALSE
502  452,Drapion,Poison,Dark,70,90,110,60,75,95,4,F...
503  453,Croagunk,Poison,Fighting,48,61,40,61,40,50...

                                                1,Type  \
497                                                NaN
498  Lucario,Fighting,Steel,70,145,88,140,70,112,4,...
499                                                NaN
500                                                NaN
501                                                NaN
502                                                NaN
503                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
497                      NaN      NaN                             NaN
498                      NaN      NaN                             NaN
499                      NaN      NaN                             NaN
500                      NaN      NaN                             NaN
501                      NaN      NaN                             NaN
502                      NaN      NaN                             NaN
503                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
504  454,Toxicroak,Poison,Fighting,83,106,65,86,65,...     NaN
505    455,Carnivine,Grass,,74,100,72,90,72,46,4,FALSE     NaN
506       456,Finneon,Water,,49,49,56,49,61,66,4,FALSE     NaN
507      457,Lumineon,Water,,69,69,76,69,86,91,4,FALSE     NaN
508  458,Mantyke,Water,Flying,45,20,50,60,120,50,4,...     NaN
509     459,Snover,Grass,Ice,60,62,50,62,60,40,4,FALSE     NaN
510  460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
504                      NaN      NaN                             NaN
505                      NaN      NaN                             NaN
506                      NaN      NaN                             NaN
507                      NaN      NaN                             NaN
508                      NaN      NaN                             NaN
509                      NaN      NaN                             NaN
510                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
511                                  460,AbomasnowMega
512   461,Weavile,Dark,Ice,70,120,65,45,85,125,4,FALSE
513  462,Magnezone,Electric,Steel,70,70,115,130,90,...
514  463,Lickilicky,Normal,,110,85,95,80,95,50,4,FALSE
515  464,Rhyperior,Ground,Rock,115,140,130,55,55,40...
516  465,Tangrowth,Grass,,100,100,125,110,50,50,4,F...
517  466,Electivire,Electric,,75,123,67,95,85,95,4,...

                                                1,Type  \
511  Abomasnow,Grass,Ice,90,132,105,132,105,30,4,FALSE
512                                                NaN
513                                                NaN
514                                                NaN
515                                                NaN
516                                                NaN
517                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
511                      NaN      NaN                             NaN
512                      NaN      NaN                             NaN
513                      NaN      NaN                             NaN
514                      NaN      NaN                             NaN
515                      NaN      NaN                             NaN
516                      NaN      NaN                             NaN
517                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
518     467,Magmortar,Fire,,75,95,67,125,95,83,4,FALSE     NaN
519  468,Togekiss,Fairy,Flying,85,50,95,120,115,80,...     NaN
520  469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,FALSE     NaN
521     470,Leafeon,Grass,,65,110,130,60,65,95,4,FALSE     NaN
522       471,Glaceon,Ice,,65,60,110,130,95,65,4,FALSE     NaN
523  472,Gliscor,Ground,Flying,75,95,125,45,75,95,4...     NaN
524  473,Mamoswine,Ice,Ground,110,130,80,70,60,80,4...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
518                      NaN      NaN                             NaN
519                      NaN      NaN                             NaN
520                      NaN      NaN                             NaN
521                      NaN      NaN                             NaN
522                      NaN      NaN                             NaN
523                      NaN      NaN                             NaN
524                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
525   474,Porygon-Z,Normal,,85,80,70,135,75,90,4,FALSE
526  475,Gallade,Psychic,Fighting,68,125,65,65,115,...
527                                    475,GalladeMega
528  476,Probopass,Rock,Steel,60,55,145,75,150,40,4...
529   477,Dusknoir,Ghost,,45,100,135,65,135,45,4,FALSE
530  478,Froslass,Ice,Ghost,70,80,70,80,70,110,4,FALSE
531  479,Rotom,Electric,Ghost,50,50,77,95,77,91,4,F...

                                                1,Type  \
525                                                NaN
526                                                NaN
527  Gallade,Psychic,Fighting,68,165,95,65,115,110,...
528                                                NaN
529                                                NaN
530                                                NaN
531                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
525                      NaN      NaN                             NaN
526                      NaN      NaN                             NaN
527                      NaN      NaN                             NaN
528                      NaN      NaN                             NaN
529                      NaN      NaN                             NaN
530                      NaN      NaN                             NaN
531                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
532                                      479,RotomHeat
533                                      479,RotomWash
534                                     479,RotomFrost
535                                       479,RotomFan
536                                       479,RotomMow
537       480,Uxie,Psychic,,75,75,130,75,130,95,4,TRUE
538  481,Mesprit,Psychic,,80,105,105,105,105,80,4,TRUE

                                                1,Type  \
532   Rotom,Electric,Fire,50,65,107,105,107,86,4,FALSE
533  Rotom,Electric,Water,50,65,107,105,107,86,4,FALSE
534    Rotom,Electric,Ice,50,65,107,105,107,86,4,FALSE
535  Rotom,Electric,Flying,50,65,107,105,107,86,4,F...
536  Rotom,Electric,Grass,50,65,107,105,107,86,4,FALSE
537                                                NaN
538                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
532                      NaN      NaN                             NaN
533                      NaN      NaN                             NaN
534                      NaN      NaN                             NaN
535                      NaN      NaN                             NaN
536                      NaN      NaN                             NaN
537                      NaN      NaN                             NaN
538                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
539     482,Azelf,Psychic,,75,125,70,125,70,115,4,TRUE
540  483,Dialga,Steel,Dragon,100,120,120,150,100,90...
541  484,Palkia,Water,Dragon,90,120,100,150,120,100...
542  485,Heatran,Fire,Steel,91,90,106,130,106,77,4,...
543  486,Regigigas,Normal,,110,160,110,80,110,100,4...
544                                487,GiratinaAltered
545                                 487,GiratinaOrigin

                                               1,Type  \
539                                               NaN
540                                               NaN
541                                               NaN
542                                               NaN
543                                               NaN
544  Forme,Ghost,Dragon,150,100,120,100,120,90,4,TRUE
545  Forme,Ghost,Dragon,150,120,100,120,100,90,4,TRUE

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
539                      NaN      NaN                             NaN
540                      NaN      NaN                             NaN
541                      NaN      NaN                             NaN
542                      NaN      NaN                             NaN
543                      NaN      NaN                             NaN
544                      NaN      NaN                             NaN
545                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
546  488,Cresselia,Psychic,,120,70,120,75,130,85,4,...
547        489,Phione,Water,,80,80,80,80,80,80,4,FALSE
548  490,Manaphy,Water,,100,100,100,100,100,100,4,F...
549       491,Darkrai,Dark,,70,90,90,135,90,125,4,TRUE
550                                    492,ShayminLand
551                                     492,ShayminSky
552  493,Arceus,Normal,,120,120,120,120,120,120,4,TRUE

                                              1,Type  2,HP,Attack,Defense,Sp.  \
546                                              NaN                      NaN
547                                              NaN                      NaN
548                                              NaN                      NaN
549                                              NaN                      NaN
550      Forme,Grass,,100,100,100,100,100,100,4,TRUE                      NaN
551  Forme,Grass,Flying,100,103,75,120,75,127,4,TRUE                      NaN
552                                              NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
546      NaN                             NaN
547      NaN                             NaN
548      NaN                             NaN
549      NaN                             NaN
550      NaN                             NaN
551      NaN                             NaN
552      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
553  494,Victini,Psychic,Fire,100,100,100,100,100,1...     NaN
554         495,Snivy,Grass,,45,45,55,45,55,63,5,FALSE     NaN
555       496,Servine,Grass,,60,60,75,60,75,83,5,FALSE     NaN
556    497,Serperior,Grass,,75,75,95,75,95,113,5,FALSE     NaN
557          498,Tepig,Fire,,65,63,45,45,45,45,5,FALSE     NaN
558  499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,...     NaN
559  500,Emboar,Fire,Fighting,110,123,65,100,65,65,...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
553                      NaN      NaN                             NaN
554                      NaN      NaN                             NaN
555                      NaN      NaN                             NaN
556                      NaN      NaN                             NaN
557                      NaN      NaN                             NaN
558                      NaN      NaN                             NaN
559                      NaN      NaN                             NaN

CUHNK DF
                                         #,Name,Type  1,Type  \
560    501,Oshawott,Water,,55,55,45,63,45,45,5,FALSE     NaN
561      502,Dewott,Water,,75,75,60,83,60,60,5,FALSE     NaN
562  503,Samurott,Water,,95,100,85,108,70,70,5,FALSE     NaN
563     504,Patrat,Normal,,45,55,39,35,39,42,5,FALSE     NaN
564    505,Watchog,Normal,,60,85,69,60,69,77,5,FALSE     NaN
565   506,Lillipup,Normal,,45,60,45,25,45,55,5,FALSE     NaN
566    507,Herdier,Normal,,65,80,65,35,65,60,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
560                      NaN      NaN                             NaN
561                      NaN      NaN                             NaN
562                      NaN      NaN                             NaN
563                      NaN      NaN                             NaN
564                      NaN      NaN                             NaN
565                      NaN      NaN                             NaN
566                      NaN      NaN                             NaN
CUHNK DF
                                          #,Name,Type  1,Type  \
567  508,Stoutland,Normal,,85,110,90,45,90,80,5,FALSE     NaN
568      509,Purrloin,Dark,,41,50,37,50,37,66,5,FALSE     NaN
569      510,Liepard,Dark,,64,88,50,88,50,106,5,FALSE     NaN
570      511,Pansage,Grass,,50,53,48,53,48,64,5,FALSE     NaN
571    512,Simisage,Grass,,75,98,63,98,63,101,5,FALSE     NaN
572       513,Pansear,Fire,,50,53,48,53,48,64,5,FALSE     NaN
573     514,Simisear,Fire,,75,98,63,98,63,101,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
567                      NaN      NaN                             NaN
568                      NaN      NaN                             NaN
569                      NaN      NaN                             NaN
570                      NaN      NaN                             NaN
571                      NaN      NaN                             NaN
572                      NaN      NaN                             NaN
573                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
574       515,Panpour,Water,,50,53,48,53,48,64,5,FALSE     NaN
575     516,Simipour,Water,,75,98,63,98,63,101,5,FALSE     NaN
576       517,Munna,Psychic,,76,25,45,67,55,24,5,FALSE     NaN
577  518,Musharna,Psychic,,116,55,85,107,95,29,5,FALSE     NaN
578  519,Pidove,Normal,Flying,50,55,50,36,30,43,5,F...     NaN
579  520,Tranquill,Normal,Flying,62,77,62,50,42,65,...     NaN
580  521,Unfezant,Normal,Flying,80,115,80,65,55,93,...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
574                      NaN      NaN                             NaN
575                      NaN      NaN                             NaN
576                      NaN      NaN                             NaN
577                      NaN      NaN                             NaN
578                      NaN      NaN                             NaN
579                      NaN      NaN                             NaN
580                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
581    522,Blitzle,Electric,,45,60,32,50,32,76,5,FALSE     NaN
582  523,Zebstrika,Electric,,75,100,63,80,63,116,5,...     NaN
583     524,Roggenrola,Rock,,55,75,85,25,25,15,5,FALSE     NaN
584      525,Boldore,Rock,,70,105,105,50,40,20,5,FALSE     NaN
585     526,Gigalith,Rock,,85,135,130,60,80,25,5,FALSE     NaN
586  527,Woobat,Psychic,Flying,55,45,43,55,43,72,5,...     NaN
587  528,Swoobat,Psychic,Flying,67,57,55,77,55,114,...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
581                      NaN      NaN                             NaN
582                      NaN      NaN                             NaN
583                      NaN      NaN                             NaN
584                      NaN      NaN                             NaN
585                      NaN      NaN                             NaN
586                      NaN      NaN                             NaN
587                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
588      529,Drilbur,Ground,,60,85,40,30,45,68,5,FALSE
589  530,Excadrill,Ground,Steel,110,135,60,50,65,88...
590      531,Audino,Normal,,103,60,86,60,86,50,5,FALSE
591                                     531,AudinoMega
592    532,Timburr,Fighting,,75,80,55,25,35,35,5,FALSE
593   533,Gurdurr,Fighting,,85,105,85,40,50,40,5,FALSE
594  534,Conkeldurr,Fighting,,105,140,95,55,65,45,5...

                                               1,Type  \
588                                               NaN
589                                               NaN
590                                               NaN
591  Audino,Normal,Fairy,103,60,126,80,126,50,5,FALSE
592                                               NaN
593                                               NaN
594                                               NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
588                      NaN      NaN                             NaN
589                      NaN      NaN                             NaN
590                      NaN      NaN                             NaN
591                      NaN      NaN                             NaN
592                      NaN      NaN                             NaN
593                      NaN      NaN                             NaN
594                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
595       535,Tympole,Water,,50,50,40,50,40,64,5,FALSE     NaN
596  536,Palpitoad,Water,Ground,75,65,55,65,55,69,5...     NaN
597  537,Seismitoad,Water,Ground,105,95,75,85,75,74...     NaN
598    538,Throh,Fighting,,120,100,85,30,85,45,5,FALSE     NaN
599      539,Sawk,Fighting,,75,125,75,30,75,85,5,FALSE     NaN
600   540,Sewaddle,Bug,Grass,45,53,70,40,60,42,5,FALSE     NaN
601   541,Swadloon,Bug,Grass,55,63,90,50,80,42,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
595                      NaN      NaN                             NaN
596                      NaN      NaN                             NaN
597                      NaN      NaN                             NaN
598                      NaN      NaN                             NaN
599                      NaN      NaN                             NaN
600                      NaN      NaN                             NaN
601                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
602  542,Leavanny,Bug,Grass,75,103,80,70,80,92,5,FALSE     NaN
603  543,Venipede,Bug,Poison,30,45,59,30,39,57,5,FALSE     NaN
604  544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,...     NaN
605  545,Scolipede,Bug,Poison,60,100,89,55,69,112,5...     NaN
606  546,Cottonee,Grass,Fairy,40,27,60,37,50,66,5,F...     NaN
607  547,Whimsicott,Grass,Fairy,60,67,85,77,75,116,...     NaN
608       548,Petilil,Grass,,45,35,50,70,50,30,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
602                      NaN      NaN                             NaN
603                      NaN      NaN                             NaN
604                      NaN      NaN                             NaN
605                      NaN      NaN                             NaN
606                      NaN      NaN                             NaN
607                      NaN      NaN                             NaN
608                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
609    549,Lilligant,Grass,,70,60,75,110,75,90,5,FALSE
610      550,Basculin,Water,,70,92,65,80,55,98,5,FALSE
611  551,Sandile,Ground,Dark,50,72,35,35,35,65,5,FALSE
612  552,Krokorok,Ground,Dark,60,82,45,45,45,74,5,F...
613  553,Krookodile,Ground,Dark,95,117,80,65,70,92,...
614       554,Darumaka,Fire,,70,90,45,15,45,50,5,FALSE
615                             555,DarmanitanStandard

                                     1,Type  2,HP,Attack,Defense,Sp.  Atk,Sp.  \
609                                     NaN                      NaN      NaN
610                                     NaN                      NaN      NaN
611                                     NaN                      NaN      NaN
612                                     NaN                      NaN      NaN
613                                     NaN                      NaN      NaN
614                                     NaN                      NaN      NaN
615  Mode,Fire,,105,140,55,30,55,95,5,FALSE                      NaN      NaN

     Def,Speed,Generation,Legendary
609                             NaN
610                             NaN
611                             NaN
612                             NaN
613                             NaN
614                             NaN
615                             NaN
CUHNK DF
                                           #,Name,Type  \
616                                  555,DarmanitanZen
617     556,Maractus,Grass,,75,86,67,106,67,60,5,FALSE
618     557,Dwebble,Bug,Rock,50,65,85,35,35,55,5,FALSE
619    558,Crustle,Bug,Rock,70,95,125,65,75,45,5,FALSE
620  559,Scraggy,Dark,Fighting,50,75,70,35,70,48,5,...
621  560,Scrafty,Dark,Fighting,65,90,115,45,115,58,...
622  561,Sigilyph,Psychic,Flying,72,58,80,103,80,97...

                                              1,Type  2,HP,Attack,Defense,Sp.  \
616  Mode,Fire,Psychic,105,30,105,140,105,55,5,FALSE                      NaN
617                                              NaN                      NaN
618                                              NaN                      NaN
619                                              NaN                      NaN
620                                              NaN                      NaN
621                                              NaN                      NaN
622                                              NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
616      NaN                             NaN
617      NaN                             NaN
618      NaN                             NaN
619      NaN                             NaN
620      NaN                             NaN
621      NaN                             NaN
622      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
623        562,Yamask,Ghost,,38,30,85,55,65,30,5,FALSE     NaN
624  563,Cofagrigus,Ghost,,58,50,145,95,105,30,5,FALSE     NaN
625  564,Tirtouga,Water,Rock,54,78,103,53,45,22,5,F...     NaN
626  565,Carracosta,Water,Rock,74,108,133,83,65,32,...     NaN
627  566,Archen,Rock,Flying,55,112,45,74,45,70,5,FALSE     NaN
628  567,Archeops,Rock,Flying,75,140,65,112,65,110,...     NaN
629     568,Trubbish,Poison,,50,50,62,40,62,65,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
623                      NaN      NaN                             NaN
624                      NaN      NaN                             NaN
625                      NaN      NaN                             NaN
626                      NaN      NaN                             NaN
627                      NaN      NaN                             NaN
628                      NaN      NaN                             NaN
629                      NaN      NaN                             NaN
CUHNK DF
                                          #,Name,Type  1,Type  \
630    569,Garbodor,Poison,,80,95,82,60,82,75,5,FALSE     NaN
631         570,Zorua,Dark,,40,65,40,80,40,65,5,FALSE     NaN
632    571,Zoroark,Dark,,60,105,60,120,60,105,5,FALSE     NaN
633    572,Minccino,Normal,,55,50,40,40,40,75,5,FALSE     NaN
634   573,Cinccino,Normal,,75,95,60,65,60,115,5,FALSE     NaN
635    574,Gothita,Psychic,,45,30,50,55,65,45,5,FALSE     NaN
636  575,Gothorita,Psychic,,60,45,70,75,85,55,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
630                      NaN      NaN                             NaN
631                      NaN      NaN                             NaN
632                      NaN      NaN                             NaN
633                      NaN      NaN                             NaN
634                      NaN      NaN                             NaN
635                      NaN      NaN                             NaN
636                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
637  576,Gothitelle,Psychic,,70,55,95,95,110,65,5,F...     NaN
638    577,Solosis,Psychic,,45,30,40,105,50,20,5,FALSE     NaN
639    578,Duosion,Psychic,,65,40,50,125,60,30,5,FALSE     NaN
640  579,Reuniclus,Psychic,,110,65,75,125,85,30,5,F...     NaN
641  580,Ducklett,Water,Flying,62,44,50,44,50,55,5,...     NaN
642  581,Swanna,Water,Flying,75,87,63,87,63,98,5,FALSE     NaN
643       582,Vanillite,Ice,,36,50,50,65,60,44,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
637                      NaN      NaN                             NaN
638                      NaN      NaN                             NaN
639                      NaN      NaN                             NaN
640                      NaN      NaN                             NaN
641                      NaN      NaN                             NaN
642                      NaN      NaN                             NaN
643                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
644       583,Vanillish,Ice,,51,65,65,80,75,59,5,FALSE     NaN
645      584,Vanilluxe,Ice,,71,95,85,110,95,79,5,FALSE     NaN
646  585,Deerling,Normal,Grass,60,60,50,40,50,75,5,...     NaN
647  586,Sawsbuck,Normal,Grass,80,100,70,60,70,95,5...     NaN
648  587,Emolga,Electric,Flying,55,75,60,75,60,103,...     NaN
649      588,Karrablast,Bug,,50,75,45,40,45,60,5,FALSE     NaN
650  589,Escavalier,Bug,Steel,70,135,105,60,105,20,...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
644                      NaN      NaN                             NaN
645                      NaN      NaN                             NaN
646                      NaN      NaN                             NaN
647                      NaN      NaN                             NaN
648                      NaN      NaN                             NaN
649                      NaN      NaN                             NaN
650                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
651  590,Foongus,Grass,Poison,69,55,45,55,55,15,5,F...     NaN
652  591,Amoonguss,Grass,Poison,114,85,70,85,80,30,...     NaN
653  592,Frillish,Water,Ghost,55,40,50,65,85,40,5,F...     NaN
654  593,Jellicent,Water,Ghost,100,60,70,85,105,60,...     NaN
655    594,Alomomola,Water,,165,75,80,40,45,65,5,FALSE     NaN
656  595,Joltik,Bug,Electric,50,47,50,57,50,65,5,FALSE     NaN
657  596,Galvantula,Bug,Electric,70,77,60,97,60,108...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
651                      NaN      NaN                             NaN
652                      NaN      NaN                             NaN
653                      NaN      NaN                             NaN
654                      NaN      NaN                             NaN
655                      NaN      NaN                             NaN
656                      NaN      NaN                             NaN
657                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
658  597,Ferroseed,Grass,Steel,44,50,91,24,86,10,5,...     NaN
659  598,Ferrothorn,Grass,Steel,74,94,131,54,116,20...     NaN
660         599,Klink,Steel,,40,55,70,45,60,30,5,FALSE     NaN
661         600,Klang,Steel,,60,80,95,70,85,50,5,FALSE     NaN
662   601,Klinklang,Steel,,60,100,115,70,85,90,5,FALSE     NaN
663     602,Tynamo,Electric,,35,55,40,45,40,60,5,FALSE     NaN
664  603,Eelektrik,Electric,,65,85,70,75,70,40,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
658                      NaN      NaN                             NaN
659                      NaN      NaN                             NaN
660                      NaN      NaN                             NaN
661                      NaN      NaN                             NaN
662                      NaN      NaN                             NaN
663                      NaN      NaN                             NaN
664                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
665  604,Eelektross,Electric,,85,115,80,105,80,50,5...     NaN
666      605,Elgyem,Psychic,,55,55,55,85,55,30,5,FALSE     NaN
667   606,Beheeyem,Psychic,,75,75,75,125,95,40,5,FALSE     NaN
668   607,Litwick,Ghost,Fire,50,30,55,65,55,20,5,FALSE     NaN
669   608,Lampent,Ghost,Fire,60,40,60,95,60,55,5,FALSE     NaN
670  609,Chandelure,Ghost,Fire,60,55,90,145,90,80,5...     NaN
671         610,Axew,Dragon,,46,87,60,30,40,57,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
665                      NaN      NaN                             NaN
666                      NaN      NaN                             NaN
667                      NaN      NaN                             NaN
668                      NaN      NaN                             NaN
669                      NaN      NaN                             NaN
670                      NaN      NaN                             NaN
671                      NaN      NaN                             NaN

CUHNK DF
                                        #,Name,Type  1,Type  \
672  611,Fraxure,Dragon,,66,117,70,40,50,67,5,FALSE     NaN
673  612,Haxorus,Dragon,,76,147,90,60,70,97,5,FALSE     NaN
674      613,Cubchoo,Ice,,55,70,40,60,40,40,5,FALSE     NaN
675     614,Beartic,Ice,,95,110,80,70,80,50,5,FALSE     NaN
676  615,Cryogonal,Ice,,70,50,30,95,135,105,5,FALSE     NaN
677      616,Shelmet,Bug,,50,40,85,40,65,25,5,FALSE     NaN
678   617,Accelgor,Bug,,80,70,40,100,60,145,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
672                      NaN      NaN                             NaN
673                      NaN      NaN                             NaN
674                      NaN      NaN                             NaN
675                      NaN      NaN                             NaN
676                      NaN      NaN                             NaN
677                      NaN      NaN                             NaN
678                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
679  618,Stunfisk,Ground,Electric,109,66,84,81,99,3...     NaN
680    619,Mienfoo,Fighting,,45,85,50,55,50,65,5,FALSE     NaN
681  620,Mienshao,Fighting,,65,125,60,95,60,105,5,F...     NaN
682   621,Druddigon,Dragon,,77,120,90,60,90,48,5,FALSE     NaN
683  622,Golett,Ground,Ghost,59,74,50,35,50,35,5,FALSE     NaN
684  623,Golurk,Ground,Ghost,89,124,80,55,80,55,5,F...     NaN
685  624,Pawniard,Dark,Steel,45,85,70,40,40,60,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
679                      NaN      NaN                             NaN
680                      NaN      NaN                             NaN
681                      NaN      NaN                             NaN
682                      NaN      NaN                             NaN
683                      NaN      NaN                             NaN
684                      NaN      NaN                             NaN
685                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
686  625,Bisharp,Dark,Steel,65,125,100,60,70,70,5,F...     NaN
687  626,Bouffalant,Normal,,95,110,95,40,95,55,5,FALSE     NaN
688  627,Rufflet,Normal,Flying,70,83,50,37,50,60,5,...     NaN
689  628,Braviary,Normal,Flying,100,123,75,57,75,80...     NaN
690  629,Vullaby,Dark,Flying,70,55,75,45,65,60,5,FALSE     NaN
691  630,Mandibuzz,Dark,Flying,110,65,105,55,95,80,...     NaN
692       631,Heatmor,Fire,,85,97,66,105,66,65,5,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
686                      NaN      NaN                             NaN
687                      NaN      NaN                             NaN
688                      NaN      NaN                             NaN
689                      NaN      NaN                             NaN
690                      NaN      NaN                             NaN
691                      NaN      NaN                             NaN
692                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
693  632,Durant,Bug,Steel,58,109,112,48,48,109,5,FALSE     NaN
694    633,Deino,Dark,Dragon,52,65,50,45,50,38,5,FALSE     NaN
695  634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,F...     NaN
696  635,Hydreigon,Dark,Dragon,92,105,90,125,90,98,...     NaN
697    636,Larvesta,Bug,Fire,55,85,55,50,55,60,5,FALSE     NaN
698  637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,...     NaN
699  638,Cobalion,Steel,Fighting,91,90,129,90,72,10...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
693                      NaN      NaN                             NaN
694                      NaN      NaN                             NaN
695                      NaN      NaN                             NaN
696                      NaN      NaN                             NaN
697                      NaN      NaN                             NaN
698                      NaN      NaN                             NaN
699                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
700  639,Terrakion,Rock,Fighting,91,129,90,72,90,10...
701  640,Virizion,Grass,Fighting,91,90,72,90,129,10...
702                              641,TornadusIncarnate
703                                641,TornadusTherian
704                             642,ThundurusIncarnate
705                               642,ThundurusTherian
706  643,Reshiram,Dragon,Fire,100,120,100,150,120,9...

                                                1,Type  \
700                                                NaN
701                                                NaN
702          Forme,Flying,,79,115,70,125,80,111,5,TRUE
703          Forme,Flying,,79,100,80,110,90,121,5,TRUE
704  Forme,Electric,Flying,79,115,70,125,80,111,5,TRUE
705  Forme,Electric,Flying,79,105,70,145,80,101,5,TRUE
706                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
700                      NaN      NaN                             NaN
701                      NaN      NaN                             NaN
702                      NaN      NaN                             NaN
703                      NaN      NaN                             NaN
704                      NaN      NaN                             NaN
705                      NaN      NaN                             NaN
706                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
707  644,Zekrom,Dragon,Electric,100,150,120,120,100...
708                              645,LandorusIncarnate
709                                645,LandorusTherian
710  646,Kyurem,Dragon,Ice,125,130,90,130,90,95,5,TRUE
711                                    646,KyuremBlack
712                                    646,KyuremWhite
713                                 647,KeldeoOrdinary

                                               1,Type  \
707                                               NaN
708   Forme,Ground,Flying,89,125,90,115,80,101,5,TRUE
709    Forme,Ground,Flying,89,145,90,105,80,91,5,TRUE
710                                               NaN
711    Kyurem,Dragon,Ice,125,170,100,120,90,95,5,TRUE
712    Kyurem,Dragon,Ice,125,120,90,170,100,95,5,TRUE
713  Forme,Water,Fighting,91,72,90,129,90,108,5,FALSE

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
707                      NaN      NaN                             NaN
708                      NaN      NaN                             NaN
709                      NaN      NaN                             NaN
710                      NaN      NaN                             NaN
711                      NaN      NaN                             NaN
712                      NaN      NaN                             NaN
713                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
714                                 647,KeldeoResolute
715                                   648,MeloettaAria
716                              648,MeloettaPirouette
717  649,Genesect,Bug,Steel,71,120,95,120,95,99,5,F...
718       650,Chespin,Grass,,56,61,65,48,45,38,6,FALSE
719     651,Quilladin,Grass,,61,78,95,56,58,57,6,FALSE
720  652,Chesnaught,Grass,Fighting,88,107,122,74,75...

                                                1,Type  \
714   Forme,Water,Fighting,91,72,90,129,90,108,5,FALSE
715  Forme,Normal,Psychic,100,77,77,128,128,90,5,FALSE
716  Forme,Normal,Fighting,100,128,90,77,77,128,5,F...
717                                                NaN
718                                                NaN
719                                                NaN
720                                                NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
714                      NaN      NaN                             NaN
715                      NaN      NaN                             NaN
716                      NaN      NaN                             NaN
717                      NaN      NaN                             NaN
718                      NaN      NaN                             NaN
719                      NaN      NaN                             NaN
720                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
721       653,Fennekin,Fire,,40,45,40,62,60,60,6,FALSE     NaN
722        654,Braixen,Fire,,59,59,58,90,70,73,6,FALSE     NaN
723  655,Delphox,Fire,Psychic,75,69,72,114,100,104,...     NaN
724       656,Froakie,Water,,41,56,40,62,44,71,6,FALSE     NaN
725     657,Frogadier,Water,,54,63,52,83,56,97,6,FALSE     NaN
726  658,Greninja,Water,Dark,72,95,67,103,71,122,6,...     NaN
727     659,Bunnelby,Normal,,38,36,38,32,36,57,6,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
721                      NaN      NaN                             NaN
722                      NaN      NaN                             NaN
723                      NaN      NaN                             NaN
724                      NaN      NaN                             NaN
725                      NaN      NaN                             NaN
726                      NaN      NaN                             NaN
727                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
728  660,Diggersby,Normal,Ground,85,56,77,50,77,78,...     NaN
729  661,Fletchling,Normal,Flying,45,50,43,40,38,62...     NaN
730  662,Fletchinder,Fire,Flying,62,73,55,56,52,84,...     NaN
731  663,Talonflame,Fire,Flying,78,81,71,74,69,126,...     NaN
732      664,Scatterbug,Bug,,38,35,40,27,25,35,6,FALSE     NaN
733          665,Spewpa,Bug,,45,22,60,27,30,29,6,FALSE     NaN
734  666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
728                      NaN      NaN                             NaN
729                      NaN      NaN                             NaN
730                      NaN      NaN                             NaN
731                      NaN      NaN                             NaN
732                      NaN      NaN                             NaN
733                      NaN      NaN                             NaN
734                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
735   667,Litleo,Fire,Normal,62,50,58,73,54,72,6,FALSE     NaN
736  668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,F...     NaN
737       669,Flabébé,Fairy,,44,38,39,61,79,42,6,FALSE     NaN
738       670,Floette,Fairy,,54,45,47,75,98,52,6,FALSE     NaN
739     671,Florges,Fairy,,78,65,68,112,154,75,6,FALSE     NaN
740        672,Skiddo,Grass,,66,65,48,62,57,52,6,FALSE     NaN
741      673,Gogoat,Grass,,123,100,62,97,81,68,6,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
735                      NaN      NaN                             NaN
736                      NaN      NaN                             NaN
737                      NaN      NaN                             NaN
738                      NaN      NaN                             NaN
739                      NaN      NaN                             NaN
740                      NaN      NaN                             NaN
741                      NaN      NaN                             NaN
CUHNK DF

                                           #,Name,Type  1,Type  \
742    674,Pancham,Fighting,,67,82,62,46,48,43,6,FALSE     NaN
743  675,Pangoro,Fighting,Dark,95,124,78,69,71,58,6...     NaN
744     676,Furfrou,Normal,,75,80,60,65,90,102,6,FALSE     NaN
745      677,Espurr,Psychic,,62,48,54,63,60,68,6,FALSE     NaN
746  678,MeowsticMale,Psychic,,74,48,76,83,81,104,6...     NaN
747  678,MeowsticFemale,Psychic,,74,48,76,83,81,104...     NaN
748  679,Honedge,Steel,Ghost,45,80,100,35,37,28,6,F...     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
742                      NaN      NaN                             NaN
743                      NaN      NaN                             NaN
744                      NaN      NaN                             NaN
745                      NaN      NaN                             NaN
746                      NaN      NaN                             NaN
747                      NaN      NaN                             NaN
748                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
749  680,Doublade,Steel,Ghost,59,110,150,45,49,35,6...
750                                 681,AegislashBlade
751                                681,AegislashShield
752      682,Spritzee,Fairy,,78,52,60,63,65,23,6,FALSE
753   683,Aromatisse,Fairy,,101,72,72,99,89,29,6,FALSE
754       684,Swirlix,Fairy,,62,48,66,59,57,49,6,FALSE
755      685,Slurpuff,Fairy,,82,80,86,85,75,72,6,FALSE

                                            1,Type  2,HP,Attack,Defense,Sp.  \
749                                            NaN                      NaN
750  Forme,Steel,Ghost,60,150,50,150,50,60,6,FALSE                      NaN
751  Forme,Steel,Ghost,60,50,150,50,150,60,6,FALSE                      NaN
752                                            NaN                      NaN
753                                            NaN                      NaN
754                                            NaN                      NaN
755                                            NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
749      NaN                             NaN
750      NaN                             NaN
751      NaN                             NaN
752      NaN                             NaN
753      NaN                             NaN
754      NaN                             NaN
755      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
756   686,Inkay,Dark,Psychic,53,54,53,37,46,45,6,FALSE     NaN
757  687,Malamar,Dark,Psychic,86,92,88,68,75,73,6,F...     NaN
758   688,Binacle,Rock,Water,42,52,67,39,56,50,6,FALSE     NaN
759  689,Barbaracle,Rock,Water,72,105,115,54,86,68,...     NaN
760  690,Skrelp,Poison,Water,50,60,60,60,60,30,6,FALSE     NaN
761  691,Dragalge,Poison,Dragon,65,75,90,97,123,44,...     NaN
762     692,Clauncher,Water,,50,53,62,58,63,44,6,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
756                      NaN      NaN                             NaN
757                      NaN      NaN                             NaN
758                      NaN      NaN                             NaN
759                      NaN      NaN                             NaN
760                      NaN      NaN                             NaN
761                      NaN      NaN                             NaN
762                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
763    693,Clawitzer,Water,,71,73,88,120,89,59,6,FALSE     NaN
764  694,Helioptile,Electric,Normal,44,38,33,61,43,...     NaN
765  695,Heliolisk,Electric,Normal,62,55,52,109,94,...     NaN
766   696,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,FALSE     NaN
767  697,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,...     NaN
768      698,Amaura,Rock,Ice,77,59,50,67,63,46,6,FALSE     NaN
769    699,Aurorus,Rock,Ice,123,77,72,99,92,58,6,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
763                      NaN      NaN                             NaN
764                      NaN      NaN                             NaN
765                      NaN      NaN                             NaN
766                      NaN      NaN                             NaN
767                      NaN      NaN                             NaN
768                      NaN      NaN                             NaN
769                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  1,Type  \
770     700,Sylveon,Fairy,,95,65,65,110,130,60,6,FALSE     NaN
771  701,Hawlucha,Fighting,Flying,78,92,75,74,63,11...     NaN
772  702,Dedenne,Electric,Fairy,67,58,57,81,67,101,...     NaN
773  703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,F...     NaN
774        704,Goomy,Dragon,,45,50,35,55,75,40,6,FALSE     NaN
775     705,Sliggoo,Dragon,,68,75,53,83,113,60,6,FALSE     NaN
776    706,Goodra,Dragon,,90,100,70,110,150,80,6,FALSE     NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
770                      NaN      NaN                             NaN
771                      NaN      NaN                             NaN
772                      NaN      NaN                             NaN
773                      NaN      NaN                             NaN
774                      NaN      NaN                             NaN
775                      NaN      NaN                             NaN
776                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
777   707,Klefki,Steel,Fairy,57,80,91,80,87,75,6,FALSE
778  708,Phantump,Ghost,Grass,43,70,48,50,60,38,6,F...
779  709,Trevenant,Ghost,Grass,85,110,76,65,82,56,6...
780                               710,PumpkabooAverage
781                                 710,PumpkabooSmall
782                                 710,PumpkabooLarge
783                                 710,PumpkabooSuper

                                         1,Type  2,HP,Attack,Defense,Sp.  \
777                                         NaN                      NaN
778                                         NaN                      NaN
779                                         NaN                      NaN
780  Size,Ghost,Grass,49,66,70,44,55,51,6,FALSE                      NaN
781  Size,Ghost,Grass,44,66,70,44,55,56,6,FALSE                      NaN
782  Size,Ghost,Grass,54,66,70,44,55,46,6,FALSE                      NaN
783  Size,Ghost,Grass,59,66,70,44,55,41,6,FALSE                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
777      NaN                             NaN
778      NaN                             NaN
779      NaN                             NaN
780      NaN                             NaN
781      NaN                             NaN
782      NaN                             NaN
783      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
784                               711,GourgeistAverage
785                                 711,GourgeistSmall
786                                 711,GourgeistLarge
787                                 711,GourgeistSuper
788        712,Bergmite,Ice,,55,69,85,32,35,28,6,FALSE
789       713,Avalugg,Ice,,95,117,184,44,46,28,6,FALSE
790  714,Noibat,Flying,Dragon,40,30,35,45,40,55,6,F...

                                           1,Type  2,HP,Attack,Defense,Sp.  \
784   Size,Ghost,Grass,65,90,122,58,75,84,6,FALSE                      NaN
785   Size,Ghost,Grass,55,85,122,58,75,99,6,FALSE                      NaN
786   Size,Ghost,Grass,75,95,122,58,75,69,6,FALSE                      NaN
787  Size,Ghost,Grass,85,100,122,58,75,54,6,FALSE                      NaN
788                                           NaN                      NaN
789                                           NaN                      NaN
790                                           NaN                      NaN

     Atk,Sp.  Def,Speed,Generation,Legendary
784      NaN                             NaN
785      NaN                             NaN
786      NaN                             NaN
787      NaN                             NaN
788      NaN                             NaN
789      NaN                             NaN
790      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
791  715,Noivern,Flying,Dragon,85,70,80,97,80,123,6...
792     716,Xerneas,Fairy,,126,131,95,131,98,99,6,TRUE
793  717,Yveltal,Dark,Flying,126,131,95,131,98,99,6...
794                                     718,Zygarde50%
795  719,Diancie,Rock,Fairy,50,100,150,100,150,50,6...
796                                    719,DiancieMega
797                                     720,HoopaHoopa

                                                1,Type  \
791                                                NaN
792                                                NaN
793                                                NaN
794    Forme,Dragon,Ground,108,100,121,81,95,95,6,TRUE
795                                                NaN
796   Diancie,Rock,Fairy,50,160,110,160,110,110,6,TRUE
797  Confined,Psychic,Ghost,80,110,60,150,130,70,6,...

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
791                      NaN      NaN                             NaN
792                      NaN      NaN                             NaN
793                      NaN      NaN                             NaN
794                      NaN      NaN                             NaN
795                      NaN      NaN                             NaN
796                      NaN      NaN                             NaN
797                      NaN      NaN                             NaN
CUHNK DF
                                           #,Name,Type  \
798                                     720,HoopaHoopa
799  721,Volcanion,Fire,Water,80,110,120,130,90,70,...

                                               1,Type  \
798  Unbound,Psychic,Dark,80,160,60,170,130,80,6,TRUE
799                                               NaN

     2,HP,Attack,Defense,Sp.  Atk,Sp.  Def,Speed,Generation,Legendary
798                      NaN      NaN                             NaN
799                      NaN      NaN                             NaN